import { createHash } from "node:crypto";
import type { AcpAccountingPeriod } from "@powerchain/acp-contracts";
import { acpRepositories } from "@powerchain/database/acp";
import { getPostgresPool } from "@powerchain/database/clients/postgres";
import { acpExecutionWallet } from "@powerchain/wallets/acp";
import { acpLedger } from "@powerchain/ledger";
import { acpAdapterGateway } from "../gateway/client";

export class AcpOperationsService{
  async scorecard(organizationId:string){const jobs=await acpRepositories.jobs.list({organizationId},{limit:500});const approvals=await acpRepositories.approvals.pending({organizationId},500);const incidents=await acpRepositories.incidents.open({organizationId});const actual=jobs.reduce((sum,job)=>sum+BigInt(job.actualSpend.rawAmount),0n),reserved=jobs.reduce((sum,job)=>sum+BigInt(job.reservedBudget.rawAmount),0n),approved=jobs.reduce((sum,job)=>sum+BigInt(job.approvedBudget.rawAmount),0n);return{jobsToday:jobs.filter(job=>job.createdAt.slice(0,10)===new Date().toISOString().slice(0,10)).length,active:jobs.filter(job=>!["completed","rejected","expired"].includes(job.state)).length,awaitingApproval:approvals.length,submitted:jobs.filter(job=>job.state==="submitted").length,reconciliationConflicts:jobs.filter(job=>job.state==="reconciliation_conflict").length,approvedSpendRaw:approved.toString(),actualSpendRaw:actual.toString(),reservedRaw:reserved.toString(),openIncidents:incidents.length,systemHealth:incidents.some((row:any)=>row.severity==="critical")?"exception":"healthy"}}
  async readiness(){const checks:Record<string,{ok:boolean;detail?:string}>={};const check=async(name:string,fn:()=>Promise<unknown>)=>{try{await fn();checks[name]={ok:true}}catch(error){checks[name]={ok:false,detail:error instanceof Error?error.message:String(error)}}};await check("database",()=>getPostgresPool().query("select 1"));await check("acpKernel",async()=>true);await check("adapter",async()=>{const health=await acpAdapterGateway.health();if(health.state!=="healthy")throw new Error(health.reason??health.state)});await check("eventInbox",()=>getPostgresPool().query("select 1 from acp_event_inbox limit 1"));await check("outbox",()=>getPostgresPool().query("select 1 from acp_outbox limit 1"));await check("approvalService",()=>getPostgresPool().query("select 1 from acp_approvals limit 1"));await check("ledger",()=>getPostgresPool().query("select 1 from acp_ledger_journals limit 1"));await check("executionWallet",()=>getPostgresPool().query("select 1 from acp_execution_accounts limit 1"));await check("reconciliationWorker",async()=>{if(process.env.POWERCHAIN_ACP_RECONCILIATION_ENABLED!=="true")throw new Error("reconciliation_disabled")});await check("compatibilityManifest",async()=>true);return{ready:Object.values(checks).every(item=>item.ok),executionReady:["database","adapter","eventInbox","outbox","approvalService","ledger","executionWallet","reconciliationWorker"].every(key=>checks[key]?.ok),checks,checkedAt:new Date().toISOString()}}
  compatibility(){return{powerchainVersion:"1.0.0",applicationVersion:"1.0.0",contractsVersion:"1.0.0",kernelVersion:"1.0.0",databaseSchemaVersion:"1.0.0",adapterVersion:"1.0.0",adapterProtocolVersion:"1.0.0",eventSchemaVersion:"1.0.0"} as const}
  async dailyClose(organizationId:string,period=new Date().toISOString().slice(0,10)){
    const jobs=await acpRepositories.jobs.list({organizationId},{limit:1000});const unknown=await acpRepositories.attempts.unknown({organizationId},1000);const incidents=await acpRepositories.incidents.open({organizationId});const activeFinancial=jobs.filter(job=>BigInt(job.reservedBudget.rawAmount)>0n&&!['completed','rejected','expired'].includes(job.state));let walletVariance=0n;try{const accounts=await getPostgresPool().query<{id:string}>("select id from acp_execution_accounts where organization_id=$1",[organizationId]);for(const row of accounts.rows)walletVariance+=BigInt((await acpExecutionWallet.reconcile(row.id)).varianceRaw)}catch{walletVariance=1n}const ledgerBalances=await acpLedger.balances(organizationId);const ledgerVariance=ledgerBalances.filter(row=>row.asset==="USDC").reduce((sum,row)=>sum+BigInt(row.balance),0n);const critical=incidents.filter((row:any)=>row.severity==="critical"&&row.status!=="resolved").length;const canClose=!unknown.length&&!activeFinancial.length&&walletVariance===0n&&ledgerVariance===0n&&!critical;const snapshot={period,reconciledJobs:jobs.filter(job=>job.lastReconciledAt).length,walletVarianceRaw:walletVariance.toString(),ledgerVarianceRaw:ledgerVariance.toString(),unknownExecutions:unknown.length,openCriticalIncidents:critical};const closeHash=createHash("sha256").update(JSON.stringify(snapshot)).digest("hex");const current:AcpAccountingPeriod={id:`apd_${crypto.randomUUID().replaceAll("-","")}`,organizationId,period,status:canClose?"closed":"exception",...snapshot,closeHash,openedAt:new Date().toISOString(),...(canClose?{closedAt:new Date().toISOString()}:{})};await acpRepositories.periods.upsert({organizationId},current);return current}
}
export const acpOperations=new AcpOperationsService();
