import fs from "node:fs";import path from "node:path";
const failures=[];const manifests=[];for(const base of [".","apps","packages"]){if(base==="."){manifests.push("package.json");continue}for(const name of fs.readdirSync(base)){const file=path.join(base,name,"package.json");if(fs.existsSync(file))manifests.push(file)}}
const names=new Set();for(const file of manifests){const p=JSON.parse(fs.readFileSync(file,"utf8"));if(p.version!=="1.0.0")failures.push(`${file}: version ${p.version}`);if(names.has(p.name))failures.push(`duplicate package name ${p.name}`);names.add(p.name)}
const lock=fs.readFileSync("pnpm-lock.yaml","utf8");for(const file of manifests){const dir=path.dirname(file)==="."?".":path.dirname(file);const marker=dir==="."?"  .:":`  ${dir}:`;if(!lock.includes(marker))failures.push(`lock importer missing: ${dir}`)}
const required=[".env.example","docs/WHITEPAPER.md","docs/api/swagger.yaml","docs/api/postman/PowerChain-v1.0.0.postman_collection.json","apps/ems/package.json","apps/platform/src/app/ems/page.tsx","apps/platform/src/app/erp/page.tsx","apps/platform/src/app/cmr/page.tsx","apps/platform/src/app/rewards/page.tsx","apps/platform/src/app/treasury/page.tsx","apps/platform/src/app/vault/page.tsx","packages/database/prisma/migrations/20260828000100_control_plane_energy_ops/migration.sql","packages/database/prisma/migrations/20260829000100_tokenized_chat_proofs/migration.sql","docs/COPILOT-TOKENIZED-CHAT.md","apps/platform/src/app/api/v1/chat/conversations/[conversationId]/credits/route.ts","apps/platform/src/app/api/v1/chat/conversations/[conversationId]/messages/[messageId]/proof/route.ts"];
for(const file of required)if(!fs.existsSync(file))failures.push(`missing ${file}`);
const openapi=fs.readFileSync("docs/api/swagger.yaml","utf8");for(const route of ["/api/v1/health","/api/v1/ready","/api/v1/projects","/api/v1/projects/{slug}","/api/v1/programs","/api/v1/token/allocations","/api/v1/powerchain/overview","/api/v1/powerchain/programs","/api/v1/solana/overview","/api/v1/solana/programs","/api/v1/solana/market","/api/v1/solana/assets/{mint}","/api/v1/config/public","/api/v1/me","/api/swagger/","/api/v1/openapi.json","/api/v1/openapi.yaml","/api/postman","/api/v1/local-energy/listings","/api/v1/local-energy/reservations","/api/v1/ems/summary","/api/v1/token-framework/cct","/api/v1/control-plane/evaluate","/api/v1/chat/conversations/{conversationId}/credits","/api/v1/chat/conversations/{conversationId}/messages/{messageId}/proof","/api/v1/credits/chat/{conversationId}"])if(!openapi.includes(route))failures.push(`OpenAPI missing ${route}`);
for(const file of ["packages/data/src/application/catalog/tokens.ts","apps/platform/src/components/tokenomics/token-tabs.tsx"])if(fs.readFileSync(file,"utf8").includes('"CRT"'))failures.push(`legacy CRT symbol remains in ${file}`);
const tokenized=fs.readFileSync("packages/credits/src/tokenized-chat.ts","utf8");if(!tokenized.includes(`CHAT_MESSAGE_UNIT_BASE_UNITS="10000000000000"`))failures.push("tokenized chat base-unit invariant missing");if(!tokenized.includes(`CHAT_MESSAGE_UNIT_PWRC="10000"`))failures.push("tokenized chat PWRC invariant missing");
if(failures.length){console.error(failures.join("\n"));process.exit(1)}console.log(`Release verification passed: ${manifests.length} workspaces at v1.0.0 with synchronized lock importers.`);
