export type SolanaCluster = "mainnet-beta" | "devnet" | "testnet" | "localnet";
const RPCS: Record<SolanaCluster,string>={"mainnet-beta":"https://api.mainnet-beta.solana.com",devnet:"https://api.devnet.solana.com",testnet:"https://api.testnet.solana.com",localnet:"http://127.0.0.1:8899"};
function cluster():SolanaCluster{const value=(process.env.SOLANA_CLUSTER??process.env.NEXT_PUBLIC_SOLANA_CLUSTER??"devnet") as SolanaCluster;return value in RPCS?value:"devnet"}
function configuredRpc(){const c=cluster();const suffix=c==="mainnet-beta"?"MAINNET":c==="devnet"?"DEVNET":c==="testnet"?"TESTNET":"LOCALNET";const direct=process.env.SOLANA_RPC_URL?.trim()||process.env[`SOLANA_${suffix}_RPC_URL`]?.trim()||process.env.HELIUS_RPC_URL?.trim()||process.env[`HELIUS_${suffix}_RPC_URL`]?.trim();if(direct)return{url:direct,source:direct.includes("helius")?"helius-url":"custom" as const,configured:true};const heliusKey=process.env.HELIUS_API_KEY?.trim();if(heliusKey&&(c==="mainnet-beta"||c==="devnet")){const host=c==="mainnet-beta"?"mainnet.helius-rpc.com":"devnet.helius-rpc.com";return{url:`https://${host}/?api-key=${encodeURIComponent(heliusKey)}`,source:"helius-key" as const,configured:true}}return{url:RPCS[c],source:"public" as const,configured:false}}
export function getSolanaRpcUrl(){return configuredRpc().url}
export function solanaRpcSource(){const value=configuredRpc();return{source:value.source,configured:value.configured,cluster:cluster()}}
export async function solanaRpc<T>(method:string,params:unknown[]=[]):Promise<T>{const r=await fetch(getSolanaRpcUrl(),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:crypto.randomUUID(),method,params}),signal:AbortSignal.timeout(10000),cache:"no-store"});if(!r.ok)throw new Error(`Solana RPC failed with ${r.status}`);const b=await r.json() as {result?:T;error?:{message?:string}};if(b.error)throw new Error(b.error.message??"Solana RPC request failed");if(b.result===undefined)throw new Error("Solana RPC returned no result");return b.result;}
export async function getSolBalance(address:string){const result=await solanaRpc<{value:number}>("getBalance",[address,{commitment:"confirmed"}]);return result.value/1_000_000_000;}
export function getAccountInfo(address:string){return solanaRpc("getAccountInfo",[address,{encoding:"jsonParsed",commitment:"confirmed"}]);}
export function getTokenAccounts(address:string){return solanaRpc("getTokenAccountsByOwner",[address,{programId:"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"},{encoding:"jsonParsed",commitment:"confirmed"}]);}
export function getSignatures(address:string,limit=20){return solanaRpc("getSignaturesForAddress",[address,{limit}]);}
export const getSolanaAccount = getAccountInfo;
export async function getSignatureStatus(signature:string){const result=await solanaRpc<{value:Array<unknown|null>}>("getSignatureStatuses",[[signature],{searchTransactionHistory:true}]);return result.value[0]??null;}
