import { createHmac } from "node:crypto";
import type { AcpExecutionAccount,AcpExecutionWalletService,WalletExecutionResult,WalletReconciliation,WalletSpendCheck } from "@powerchain/acp-contracts";
import { getPostgresPool } from "@powerchain/database/clients/postgres";

interface AccountRow{ id:string;organization_id:string;chain_id:number;address:string;purpose:string;asset:string;state:AcpExecutionAccount["state"];daily_limit_raw:string;spent_today_raw:string;wallet_provider:string }
const map=(row:AccountRow):AcpExecutionAccount=>({id:row.id,organizationId:row.organization_id,chainId:row.chain_id,address:row.address,purpose:"ACP_COMMERCE_ONLY",asset:"USDC",state:row.state,dailyLimitRaw:row.daily_limit_raw,spentTodayRaw:row.spent_today_raw,walletProvider:row.wallet_provider});
function checkedUrl(value:string,code:string){const url=new URL(value);if(url.protocol!=="https:"&&!['localhost','127.0.0.1','::1'].includes(url.hostname))throw Object.assign(new Error(`${code} requires HTTPS`),{code});return url}
function sign(body:string,secret:string){return createHmac("sha256",secret).update(body).digest("hex")}
export class PostgresAcpExecutionWalletService implements AcpExecutionWalletService{
 async getExecutionAccount(organizationId:string,chainId:number){const result=await getPostgresPool().query<AccountRow>(`select * from acp_execution_accounts where organization_id=$1 and chain_id=$2 limit 1`,[organizationId,chainId]);const row=result.rows[0];if(!row)throw Object.assign(new Error(`No restricted ACP execution account is configured for chain ${chainId}`),{code:"ACP_EXECUTION_ACCOUNT_NOT_CONFIGURED"});return map(row)}
 async assertSpendAllowed(input:WalletSpendCheck){const account=await this.getExecutionAccount(input.organizationId,input.chainId);if(account.id!==input.accountId)throw Object.assign(new Error("Execution account does not match the authorized ACP account"),{code:"ACP_WALLET_ACCOUNT_MISMATCH"});if(account.purpose!=="ACP_COMMERCE_ONLY"||account.asset!=="USDC")throw Object.assign(new Error("Wallet account is not restricted to ACP USDC commerce"),{code:"ACP_WALLET_PURPOSE_INVALID"});if(account.state!=="ACTIVE")throw Object.assign(new Error(`ACP execution account is ${account.state.toLowerCase()}`),{code:"ACP_WALLET_NOT_ACTIVE"});const requested=BigInt(input.amountRaw),remaining=BigInt(account.dailyLimitRaw)-BigInt(account.spentTodayRaw);if(requested<=0n||requested>remaining)throw Object.assign(new Error("ACP execution wallet daily spend limit would be exceeded"),{code:"ACP_WALLET_LIMIT_EXCEEDED",remainingRaw:remaining.toString()})}
 async executeSpend(input:WalletSpendCheck&{recipient:string;idempotencyKey:string}):Promise<WalletExecutionResult>{
  await this.assertSpendAllowed(input);const endpoint=process.env.POWERCHAIN_ACP_WALLET_EXECUTE_URL?.trim();const secret=process.env.POWERCHAIN_INTERNAL_SERVICE_SECRET?.trim();if(!endpoint||!secret)throw Object.assign(new Error("ACP wallet execution provider is not configured"),{code:"ACP_WALLET_EXECUTION_UNCONFIGURED"});const url=checkedUrl(endpoint,"ACP_WALLET_EXECUTION_REQUIRES_HTTPS");
  const body=JSON.stringify({organizationId:input.organizationId,accountId:input.accountId,chainId:input.chainId,asset:"USDC",amountRaw:input.amountRaw,recipient:input.recipient,businessReference:input.businessReference,idempotencyKey:input.idempotencyKey});
  try{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json","x-powerchain-internal-signature":sign(body,secret),"idempotency-key":input.idempotencyKey},body,signal:AbortSignal.timeout(30_000)});const payload=await response.json().catch(()=>null) as Partial<WalletExecutionResult>|null;if(response.status===202||payload?.status==="unknown")return{status:"unknown",errorCode:payload?.errorCode??"ACP_WALLET_EXECUTION_UNKNOWN"};if(!response.ok||!payload)return{status:"failed",errorCode:payload?.errorCode??`ACP_WALLET_HTTP_${response.status}`};if(payload.status!=="success"||!payload.transactionReference)return{status:"unknown",errorCode:"ACP_WALLET_RECEIPT_MISSING"};await getPostgresPool().query(`update acp_execution_accounts set spent_today_raw=spent_today_raw+$1,updated_at=now() where id=$2 and organization_id=$3`,[input.amountRaw,input.accountId,input.organizationId]);return{status:"success",transactionReference:payload.transactionReference,networkFeeRaw:payload.networkFeeRaw}}
  catch(error){const message=error instanceof Error?error.message.toLowerCase():String(error).toLowerCase();if(/timeout|socket|network|econnreset|aborted/.test(message))return{status:"unknown",errorCode:"ACP_WALLET_EXECUTION_UNKNOWN"};throw error}
 }
 async reconcile(accountId:string):Promise<WalletReconciliation>{const accountResult=await getPostgresPool().query<AccountRow>(`select * from acp_execution_accounts where id=$1 limit 1`,[accountId]);const row=accountResult.rows[0];if(!row)throw Object.assign(new Error("ACP execution account not found"),{code:"ACP_EXECUTION_ACCOUNT_NOT_FOUND"});const endpoint=process.env.POWERCHAIN_ACP_WALLET_RECONCILE_URL?.trim();const secret=process.env.POWERCHAIN_INTERNAL_SERVICE_SECRET?.trim();if(!endpoint||!secret)throw Object.assign(new Error("ACP wallet reconciliation provider is not configured"),{code:"ACP_WALLET_RECONCILIATION_UNCONFIGURED"});const url=checkedUrl(endpoint,"ACP_WALLET_RECONCILIATION_REQUIRES_HTTPS");const requestBody=JSON.stringify({accountId:row.id,organizationId:row.organization_id,chainId:row.chain_id,address:row.address,asset:"USDC"});const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json","x-powerchain-internal-signature":sign(requestBody,secret)},body:requestBody,signal:AbortSignal.timeout(12_000)});const body=await response.json().catch(()=>null) as Partial<WalletReconciliation>|null;if(!response.ok||!body)throw Object.assign(new Error(`ACP wallet reconciliation provider returned ${response.status}`),{code:"ACP_WALLET_RECONCILIATION_FAILED"});return{accountId:row.id,chainId:row.chain_id,confirmedBalanceRaw:String(body.confirmedBalanceRaw??"0"),observedTransactions:Array.isArray(body.observedTransactions)?body.observedTransactions:[],varianceRaw:String(body.varianceRaw??"0"),observedAt:typeof body.observedAt==="string"?body.observedAt:new Date().toISOString()}}
 async registerAccount(input:{organizationId:string;chainId:number;address:string;dailyLimitRaw:string;walletProvider:string;state?:AcpExecutionAccount["state"]}){const id=`acw_${crypto.randomUUID().replaceAll("-","")}`;const result=await getPostgresPool().query<AccountRow>(`insert into acp_execution_accounts(id,organization_id,chain_id,address,purpose,asset,state,daily_limit_raw,spent_today_raw,wallet_provider) values($1,$2,$3,$4,'ACP_COMMERCE_ONLY','USDC',$5,$6,0,$7) on conflict(organization_id,chain_id) do update set address=excluded.address,state=excluded.state,daily_limit_raw=excluded.daily_limit_raw,wallet_provider=excluded.wallet_provider,updated_at=now() returning *`,[id,input.organizationId,input.chainId,input.address,input.state??"ACTIVE",input.dailyLimitRaw,input.walletProvider]);return map(result.rows[0]!)}
}
export const acpExecutionWallet=new PostgresAcpExecutionWalletService();
