packages:
- .
- apps/*
- packages/*
minimumReleaseAge: 1440
pmOnFail: ignore
engineStrict: true
verifyDepsBeforeRun: error
trustLockfile: true
blockExoticSubdeps: true
strictDepBuilds: true
strictPeerDependencies: false
autoInstallPeers: true
dedupePeers: true
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  bufferutil: true
  utf-8-validate: true
  protobufjs: true
  tiny-secp256k1: true
  blake-hash: true
  bigint-buffer: true
  esbuild: true
  '@stellar/stellar-sdk': false
  core-js-pure: false
  usb: false
overrides:
  next@16.2.12>postcss: 8.5.26
  next@16.2.12>sharp: '-'
  '@prisma/config@6.19.3>deepmerge-ts': 8.0.2
  jayson@4.3.0>uuid: 11.1.1
  '@cetusprotocol/cetus-sui-clmm-sdk@5.4.0>uuid': 11.1.1
