import { createHash } from "node:crypto";
import { acpRepositories,withAcpTransaction } from "@powerchain/database/acp";
import { transitionJob } from "@powerchain/acp-domain";
import { evidenceVault } from "@powerchain/evidence";

function content(entry:any){if(typeof entry?.content==="string")return entry.content;if(typeof entry?.message==="string")return entry.message;if(typeof entry?.data?.content==="string")return entry.data.content;return JSON.stringify(entry)}
async function processRow(row:any){const organizationId=String(row.organization_id),externalJobId=String(row.external_job_id),chainId=Number(row.chain_id);const job=await acpRepositories.jobs.findByExternalJob(chainId,externalJobId);if(!job||job.organizationId!==organizationId)throw Object.assign(new Error("External ACP event cannot be bound to a tenant job"),{code:"ACP_EVENT_TENANT_BINDING_FAILED"});const type=String(row.mapped_event_type??"powerchain.acp.external.message_observed.v1");
  if(type==="powerchain.acp.external.submission_observed.v1"){await evidenceVault.ingest({organizationId,jobId:job.id,providerId:job.providerId,content:content(row.payload),source:"powerchain-acp",classification:"ACP_DELIVERABLE",truthTier:"T1"})}
  await withAcpTransaction(organizationId,async tx=>{const context={organizationId,transaction:tx};const locked=await acpRepositories.jobs.lock(context,job.id);if(!locked)return;let next={...locked,lastExternalEventAt:new Date(row.received_at).toISOString(),version:locked.version+1,updatedAt:new Date().toISOString()};if(type==="powerchain.acp.external.job_created.v1"&&["creating","reconciling"].includes(locked.state))next={...transitionJob(locked,"created"),lastExternalEventAt:new Date(row.received_at).toISOString()};else if(type==="powerchain.acp.external.submission_observed.v1"&&["funded","in_progress","revision_requested"].includes(locked.state))next={...transitionJob(locked,"submitted"),lastExternalEventAt:new Date(row.received_at).toISOString()};await acpRepositories.jobs.save(context,next,locked.version);await acpRepositories.audit.append(context,{actorType:"service",actorId:"acp-event-worker",action:type,resourceType:"AcpJob",resourceId:job.id,metadata:{externalJobId,eventFingerprint:row.event_fingerprint},requestId:`evt_${row.id}`,traceId:`evt_${row.id}`,correlationId:job.id,causationId:String(row.id)});if(["powerchain.acp.external.funding_observed.v1","powerchain.acp.external.completion_observed.v1","powerchain.acp.external.rejection_observed.v1"].includes(type))await acpRepositories.outbox.append(context,{topic:"powerchain.acp.reconciliation.requested.v1",aggregateType:"AcpJob",aggregateId:job.id,payload:{jobId:job.id,sourceEvent:type},requestId:`evt_${row.id}`,traceId:`evt_${row.id}`,correlationId:job.id,causationId:String(row.id)})})}
export async function runAcpEventProcessingCycle(workerId:string,limit=100){const rows=await acpRepositories.inbox.claimBatch(workerId,limit,90);let processed=0,failed=0;for(const row of rows){try{await processRow(row);await acpRepositories.inbox.complete(String(row.id));processed++}catch(error){await acpRepositories.inbox.fail(String(row.id),error instanceof Error?error.message:String(error));failed++}}return{claimed:rows.length,processed,failed}}
export async function resolveOrphanEvents(limit=50){const rows=await acpRepositories.orphans.unresolved(limit);let resolved=0;for(const row of rows){try{const job=await acpRepositories.jobs.findByExternalJob(Number(row.chain_id),String(row.external_job_id));if(!job)continue;await acpRepositories.inbox.receive({organizationId:job.organizationId},{source:"powerchain-acp",chainId:Number(row.chain_id),externalJobId:String(row.external_job_id),eventFingerprint:String(row.event_fingerprint),externalEventType:row.external_event_type?String(row.external_event_type) as any:undefined,mappedEventType:row.mapped_event_type?String(row.mapped_event_type) as any:undefined,payload:row.payload,receivedAt:new Date(row.received_at).toISOString()});await acpRepositories.orphans.resolve(String(row.id),job.organizationId);resolved++}catch(error){await acpRepositories.orphans.fail(String(row.id),error instanceof Error?error.message:String(error))}}return{examined:rows.length,resolved}}
