export const DEVICE_CONTROL_VERSION="1.0.0" as const;
export type DeviceCommandType="RESTART"|"ENTER_MAINTENANCE"|"EXIT_MAINTENANCE"|"SYNC_TIME"|"REQUEST_DIAGNOSTICS"|"REFRESH_CONFIGURATION";
export type DeviceCommandState="DRAFT"|"REVIEW_REQUIRED"|"APPROVED"|"DISPATCHED"|"CONFIRMED"|"FAILED"|"UNKNOWN"|"REJECTED";
export interface DeviceCommandIntent{id:string;organizationId:string;deviceId:string;type:DeviceCommandType;requestedBy:{type:"user"|"agent";id:string};expectedDeviceVersion:number;reason:string;state:DeviceCommandState;requestId:string;traceId:string;correlationId:string;createdAt:string}
export interface DeviceCommandPolicy{deviceType:string;supportedCommands:DeviceCommandType[];requiresApproval:DeviceCommandType[];requiresMaintenanceMode:DeviceCommandType[];minimumHealthScore:number;maximumTelemetryAgeSeconds:number}
export interface DeviceCommandContext{online:boolean;maintenanceMode:boolean;healthScore:number;telemetryAgeSeconds:number;version:number}
export interface DeviceCommandDecision{allowed:boolean;requiresApproval:boolean;reasons:string[]}
export function evaluateDeviceCommand(intent:DeviceCommandIntent,policy:DeviceCommandPolicy,context:DeviceCommandContext):DeviceCommandDecision{const reasons:string[]=[];if(!policy.supportedCommands.includes(intent.type))reasons.push("Command is not supported by this device.");if(!context.online)reasons.push("Device is offline.");if(context.version!==intent.expectedDeviceVersion)reasons.push("Device version changed; refresh before dispatch.");if(context.telemetryAgeSeconds>policy.maximumTelemetryAgeSeconds)reasons.push("Latest device telemetry is stale.");if(context.healthScore<policy.minimumHealthScore&&intent.type==="RESTART")reasons.push("Health score is below the safe restart threshold.");if(policy.requiresMaintenanceMode.includes(intent.type)&&!context.maintenanceMode)reasons.push("Maintenance mode is required.");return{allowed:reasons.length===0,requiresApproval:policy.requiresApproval.includes(intent.type),reasons}}
export interface DeviceCommandAdapter{provider:string;supportedDeviceTypes:string[];dispatch(intent:DeviceCommandIntent):Promise<{state:"confirmed"|"unknown"|"failed";externalReference?:string;errorCode?:string}>}
