"use client";
import Link from "next/link";
import { Activity,ArrowRight,BatteryCharging,CloudSun,PlugZap,RefreshCw,SunMedium,TriangleAlert,Wifi } from "lucide-react";
import { useMyEnergy } from "@/hooks/use-my-energy";
function energy(wh:string|undefined){const value=BigInt(wh??"0");if(value>=1_000_000n)return`${(Number(value)/1_000_000).toFixed(2)} MWh`;if(value>=1_000n)return`${(Number(value)/1_000).toFixed(1)} kWh`;return`${value} Wh`}
function watts(value:string|undefined){if(!value)return"—";const w=BigInt(value);return w>=1000n?`${(Number(w)/1000).toFixed(1)} kW`:`${w} W`}
export function MyEnergyDashboard(){const{data,loading,error,refresh}=useMyEnergy();if(loading)return <div className="my-energy-skeleton"><div/><div/><div/><div/></div>;if(error)return <section className="panel p-5"><p className="eyebrow">MY ENERGY</p><h1 className="mt-2 text-2xl font-semibold">Energy data is temporarily unavailable.</h1><p className="mt-2 text-sm text-[var(--muted)]">{error}</p><button className="button button-secondary mt-4" onClick={()=>void refresh()}><RefreshCw/>Retry</button></section>;if(!data)return null;const{s,devices}= {s:data.summary,devices:data.devices};const unconfigured=data.state==="UNCONFIGURED";return <div className="my-energy-page">
 <header className="my-energy-hero"><div><p className="eyebrow">MY ENERGY</p><h1>Your connected energy workspace.</h1><p>Monitor verified generation, consumption, connected hardware and community energy opportunities from one operational surface.</p></div><div className="flex flex-wrap gap-2"><button className="button button-secondary" onClick={()=>void refresh()}><RefreshCw/>Refresh</button><Link href="/my-energy/devices" className="button button-primary">Connected devices <ArrowRight/></Link></div></header>
 {unconfigured&&<div className="my-energy-notice"><Wifi/><div><strong>Energy monitoring is not configured yet.</strong><span>Connect meters, inverters or IoT/DePIN devices to populate verified energy data. PowerChain will not synthesize a balance.</span></div><Link href="/settings/integrations">Configure integrations</Link></div>}
 <section className="my-energy-primary-grid">
  <article className="my-energy-primary"><span>Verified energy today</span><strong>{energy(s.verifiedEnergyWh)}</strong><small>{s.sourceMode} · physical evidence remains authoritative</small><div className="my-energy-flow-mini"><span>Generation {energy(s.generationWh)}</span><i/><span>Consumption {energy(s.consumptionWh)}</span></div></article>
  <div className="my-energy-secondary-grid"><article><SunMedium/><span>Generation</span><strong>{energy(s.generationWh)}</strong></article><article><PlugZap/><span>Consumption</span><strong>{energy(s.consumptionWh)}</strong></article><article><BatteryCharging/><span>Self-consumed</span><strong>{energy(s.selfConsumptionWh)}</strong></article><article><CloudSun/><span>Carbon avoided</span><strong>{Number(BigInt(s.carbonAvoidedGrams??"0"))/1000} kg</strong></article></div>
 </section>
 <section className="my-energy-attention"><div><TriangleAlert/><span><strong>{s.attentionDevices} devices require attention</strong><small>{s.staleDevices} have stale telemetry. Device commands remain approval controlled.</small></span></div><Link href="/my-energy/devices">Review devices <ArrowRight/></Link></section>
 <section className="grid gap-4 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)]">
  <article className="panel min-w-0 p-5"><div className="section-row"><div><p className="eyebrow">CONNECTED DEVICES</p><h2>Energy infrastructure</h2></div><Link href="/my-energy/devices">View all</Link></div><div className="device-list">{devices.length?devices.slice(0,5).map(device=><Link href={`/my-energy/devices?device=${encodeURIComponent(device.id)}`} key={device.id}><span className={`device-health-dot ${device.status.toLowerCase()}`}/><span className="min-w-0"><strong>{device.manufacturer} {device.model}</strong><small>{device.kind.replaceAll("_"," ")} · {device.network} · health {device.healthScore}%</small></span><b>{watts(device.currentOutputW)}</b></Link>):<div className="empty-row">No connected devices yet. <Link href="/settings/integrations">Connect hardware</Link></div>}</div></article>
  <article className="panel min-w-0 p-5"><div className="section-row"><div><p className="eyebrow">ENERGY MONITORING</p><h2>Evidence pipeline</h2></div><Activity/></div><ol className="energy-evidence-steps"><li><span>01</span><div><strong>Devices & meters</strong><small>Raw telemetry remains off-chain.</small></div></li><li><span>02</span><div><strong>Energy Ledger</strong><small>Validated periods and evidence.</small></div></li><li><span>03</span><div><strong>Proof / settlement</strong><small>Only hashes, ownership and settlement move on-chain.</small></div></li></ol><Link className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-emerald-700" href="/my-energy/monitoring">Open monitoring <ArrowRight className="h-4 w-4"/></Link></article>
 </section>
 <SolarShareCards/>
 </div>}
function SolarShareCards(){const items=[{title:"Solana Wallet Integration",body:"Connect a Solana wallet for approved energy transactions and reward claims.",icon:PlugZap},{title:"Solar Panel Monitoring",body:"Monitor solar production, inverter health and verified meter evidence.",icon:SunMedium},{title:"IoT Device Integration",body:"Connect smart meters, IoT devices, Helium and DePIN infrastructure.",icon:Wifi},{title:"Energy Analytics",body:"Understand generation, consumption, self-consumption and revenue context.",icon:Activity},{title:"Energy Marketplace",body:"Review local energy listings backed by canonical physical-energy reservations.",icon:CloudSun},{title:"Peer-to-Peer Trading",body:"Prepare local energy trades with explicit reservation, delivery and settlement states.",icon:ArrowRight}];return <section className="solarshare-section"><div><p className="eyebrow">SOLARSHARE · COMMUNITY DEPİN</p><h2>Empowering communities with connected energy infrastructure.</h2><p>SolarShare combines verified solar production, connected hardware and Solana infrastructure without turning blockchain records into a substitute for physical meter evidence.</p></div><div className="solarshare-grid">{items.map(({title,body,icon:Icon})=><article key={title}><span><Icon/></span><strong>{title}</strong><p>{body}</p></article>)}</div></section>}
