"use client";
import { useEffect,useMemo,useState } from "react";
import { Building2,Factory,Leaf,Network,Search,ShieldCheck,Users,Zap } from "lucide-react";
import { Shell } from "@/components/shell";

type Participant={id:string;publicId:string;name:string;type:string;country:string;region?:string;capabilities:string[];energySources:string[];markets:string[];verified:boolean;publicProfile:boolean};
const types=[
 ["all","All"],["consumer","Consumers"],["prosumer","Prosumers"],["retailer","Retailers"],["renewable_generator","Renewables"],["grid_operator","Power grids"],["utility","Utilities"],["community","Communities"],["energy_company","Energy companies"],
] as const;
function icon(type:string){if(type==="renewable_generator")return Leaf;if(type==="grid_operator"||type==="utility")return Zap;if(type==="prosumer"||type==="consumer"||type==="community")return Users;if(type==="retailer"||type==="energy_company")return Building2;return Factory}
export function EnergyNetworkWorkspace(){
 const[q,setQ]=useState("");const[type,setType]=useState("all");const[items,setItems]=useState<Participant[]>([]);const[state,setState]=useState<"LOADING"|"READY"|"EMPTY"|"ERROR">("LOADING");const[error,setError]=useState("");
 const query=useMemo(()=>{const p=new URLSearchParams();if(q.trim())p.set("q",q.trim());if(type!=="all")p.set("types",type);p.set("limit","60");return p.toString()},[q,type]);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(async()=>{setState("LOADING");try{const response=await fetch(`/api/v1/energy-network/search?${query}`,{cache:"no-store",signal:controller.signal});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message??"Energy Network search failed");const next=body?.data?.participants??[];setItems(next);setState(next.length?"READY":"EMPTY");setError("")}catch(cause){if(controller.signal.aborted)return;setError(cause instanceof Error?cause.message:"Energy Network search failed");setState("ERROR")}},220);return()=>{clearTimeout(timer);controller.abort()}},[query]);
 return <Shell><div className="content-container space-y-5">
  <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">POWERCHAIN ENERGY NETWORK</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Find energy participants and infrastructure.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">Search consumers, prosumers, electricity retailers, renewable generators, power-grid operators, utilities and local-energy communities. Public profiles and your organization records are tenant-safe.</p></div><div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 text-xs"><span className="font-semibold text-emerald-700">Source</span> PostgreSQL Energy Network</div></header>
  <section className="panel p-4"><div className="flex min-h-12 items-center gap-3 rounded-xl border border-[var(--border)] px-3"><Search className="h-4 w-4 text-[var(--muted)]"/><input className="min-w-0 flex-1 bg-transparent text-base outline-none" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search participants, capabilities, regions or energy sources…"/></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{types.map(([value,label])=><button key={value} type="button" aria-pressed={type===value} onClick={()=>setType(value)} className={type===value?"shrink-0 rounded-full bg-emerald-950 px-3 py-2 text-xs font-semibold text-white":"shrink-0 rounded-full border border-[var(--border)] px-3 py-2 text-xs font-semibold"}>{label}</button>)}</div></section>
  {state==="LOADING"&&<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{Array.from({length:6},(_,i)=><div key={i} className="panel h-36 animate-pulse bg-black/[.025] dark:bg-white/[.025]"/>)}</div>}
  {state==="ERROR"&&<section className="panel p-5"><strong>Energy Network unavailable</strong><p className="mt-1 text-sm text-[var(--muted)]">{error}</p><button className="pc-button framed mt-4" onClick={()=>setQ(value=>value+" ")}>Retry</button></section>}
  {state==="EMPTY"&&<section className="panel p-8 text-center"><Network className="mx-auto h-7 w-7 text-emerald-700"/><h2 className="mt-3 text-lg font-bold">No matching participants</h2><p className="mt-1 text-sm text-[var(--muted)]">Adjust the participant type or search terms. PowerChain does not fabricate participant records.</p></section>}
  {state==="READY"&&<section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map(item=>{const Icon=icon(item.type);return <article className="panel min-w-0 p-4" key={item.id}><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-950/[.07] text-emerald-800"><Icon className="h-4 w-4"/></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h2 className="truncate text-sm font-bold">{item.name}</h2>{item.verified&&<span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-emerald-600/10 px-2 py-1 text-[10px] font-bold text-emerald-800"><ShieldCheck className="h-3 w-3"/>Verified</span>}</div><p className="mt-1 text-xs capitalize text-[var(--muted)]">{item.type.replaceAll("_"," ")} · {item.region?`${item.region}, `:""}{item.country}</p></div></div><div className="mt-4 flex flex-wrap gap-1.5">{[...item.energySources,...item.capabilities].slice(0,6).map(value=><span key={value} className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px]">{value}</span>)}</div><p className="mt-3 truncate text-[11px] text-[var(--muted)]">{item.publicId}</p></article>})}</section>}
 </div></Shell>
}
