import type { PowerChainAgentManifest } from "./index";
function manifest(input:Omit<PowerChainAgentManifest,"version">):PowerChainAgentManifest{return{version:"1.0.0",...input}}
export const powerChainAgentTeam:PowerChainAgentManifest[]=[
 manifest({id:"research-agent",name:"Research Agent",description:"Source-backed infrastructure and market research.",capabilities:["research","source-validation"],permissions:{read:["public:*","documents:*","evidence:*"],write:["reports:*"],execute:[]},networks:{},requiresApproval:[],skills:["research"],tools:["search","evidence_extract"],maxAutonomyLevel:1}),
 manifest({id:"market-agent",name:"Market Agent",description:"Market and provider analysis without trading authority.",capabilities:["market-analysis","provider-comparison"],permissions:{read:["markets:*","providers:*"],write:["reports:*"],execute:[]},networks:{solana:true,sui:true},requiresApproval:["marketplace.trade"],skills:["markets"],tools:["market_quotes","provider_compare"],maxAutonomyLevel:2}),
 manifest({id:"asset-agent",name:"Asset Agent",description:"Renewable asset health and performance intelligence.",capabilities:["asset-analysis","forecasting"],permissions:{read:["assets:*","energy:*","evidence:*"],write:["alerts:*","reports:*"],execute:[]},networks:{},requiresApproval:[],skills:["asset-health"],tools:["asset_graph","forecast_generation"],maxAutonomyLevel:2}),
 manifest({id:"device-agent",name:"Device Agent",description:"Smart meter, IoT and DePIN monitoring; device commands remain approval-controlled.",capabilities:["device-monitoring","anomaly-detection"],permissions:{read:["devices:*","telemetry:*"],write:["alerts:*","tasks:*"],execute:[]},networks:{solana:true},requiresApproval:["device.command"],skills:["device-health"],tools:["device_get_health","device_prepare_command"],maxAutonomyLevel:2}),
 manifest({id:"treasury-agent",name:"Treasury Agent",description:"Treasury analysis and allocation preparation without transfer authority.",capabilities:["treasury-analysis","reconciliation"],permissions:{read:["treasury:*","ledger:*"],write:["reports:*"],execute:[]},networks:{solana:true,sui:true},requiresApproval:["treasury.transfer"],skills:["treasury"],tools:["treasury_analyze","treasury_prepare_allocation"],maxAutonomyLevel:2}),
 manifest({id:"settlement-agent",name:"Settlement Agent",description:"Reviews settlement state and evidence boundaries.",capabilities:["settlement-analysis","reconciliation"],permissions:{read:["settlements:*","ledger:*","evidence:*"],write:["tasks:*"],execute:[]},networks:{solana:true,sui:true},requiresApproval:["transaction.prepare"],skills:["settlement"],tools:["settlement_review"],maxAutonomyLevel:2}),
 manifest({id:"compliance-agent",name:"Compliance Agent",description:"Policy and evidence compliance review.",capabilities:["compliance","policy-analysis"],permissions:{read:["policy:*","evidence:*","audit:*"],write:["reports:*"],execute:[]},networks:{},requiresApproval:[],skills:["compliance"],tools:["policy_review"],maxAutonomyLevel:1}),
 manifest({id:"anomaly-agent",name:"Anomaly Agent",description:"Detects unusual operational patterns and opens reviewable incidents.",capabilities:["anomaly-detection"],permissions:{read:["energy:*","devices:*","treasury:*","events:*"],write:["alerts:*"],execute:[]},networks:{},requiresApproval:[],skills:["anomaly"],tools:["anomaly_scan"],maxAutonomyLevel:2}),
 manifest({id:"exposure-agent",name:"Exposure Agent",description:"Evaluates operational and financial exposure.",capabilities:["risk-analysis"],permissions:{read:["assets:*","treasury:*","markets:*"],write:["reports:*"],execute:[]},networks:{},requiresApproval:[],skills:["risk"],tools:["exposure_analyze"],maxAutonomyLevel:1}),
 manifest({id:"operator-agent",name:"Operator Agent",description:"Prioritizes findings, creates tasks, assigns owners and escalates blockers; it does not replace specialist intelligence.",capabilities:["workflow-planning","task-management"],permissions:{read:["alerts:*","reports:*","tasks:*"],write:["tasks:*"],execute:[]},networks:{},requiresApproval:["transaction.prepare","device.command"],skills:["workflow"],tools:["task_prepare","workflow_prepare"],maxAutonomyLevel:2}),
];
