export const CONTROL_PLANE_VERSION="1.0.0" as const;
export type AgentAutonomyLevel=0|1|2|3|4|5;
export type AgentPermission="READ"|"ANALYZE"|"PREPARE"|"REQUEST_APPROVAL"|"EXECUTE_PREAUTHORIZED"|"AUTONOMOUS";
export interface PowerChainAgentManifest{ id:string;name:string;version:"1.0.0";description:string;capabilities:string[];permissions:{read:string[];write:string[];execute:string[]};networks:{solana?:boolean;sui?:boolean};requiresApproval:string[];skills:string[];tools:string[];maxAutonomyLevel:AgentAutonomyLevel }
export type ActionIntentType="OPEN_ASSET"|"CREATE_ALERT"|"GENERATE_REPORT"|"CREATE_TASK"|"PREPARE_TRANSACTION"|"DEVICE_COMMAND"|"MARKETPLACE_TRADE"|"TOKEN_ISSUANCE"|"TREASURY_TRANSFER";
export interface ActionIntent{id:string;organizationId:string;actor:{type:"user"|"agent"|"service";id:string};type:ActionIntentType;resource?:{type:string;id:string};payload:Record<string,unknown>;requestId:string;traceId:string;correlationId:string;createdAt:string}
export interface ControlPlaneContext{organizationId:string;userId?:string;role:string;dataClassification:"PUBLIC"|"INTERNAL"|"CONFIDENTIAL"|"RESTRICTED";permissions:string[];requestId:string;traceId:string;correlationId:string}
export interface ControlPlaneDecision{allowed:boolean;requiresApproval:boolean;reasons:string[];policyVersion:"1.0.0";intent:ActionIntent}
export interface ExecutionGatewayPort{prepare(intent:ActionIntent,decision:ControlPlaneDecision):Promise<{executionId:string;state:"prepared"|"pending_approval"}>;executePreauthorized?(executionId:string):Promise<{state:"executed"|"unknown"|"rejected";externalReference?:string}>}
const LEVEL_PERMISSION:Record<AgentAutonomyLevel,AgentPermission[]>={0:["READ"],1:["READ","ANALYZE"],2:["READ","ANALYZE","PREPARE"],3:["READ","ANALYZE","PREPARE","REQUEST_APPROVAL"],4:["READ","ANALYZE","PREPARE","REQUEST_APPROVAL","EXECUTE_PREAUTHORIZED"],5:["READ","ANALYZE","PREPARE","REQUEST_APPROVAL","EXECUTE_PREAUTHORIZED","AUTONOMOUS"]};
export function permissionForLevel(level:AgentAutonomyLevel){return [...LEVEL_PERMISSION[level]]}
export function assertAgentCapability(manifest:PowerChainAgentManifest,capability:string){if(!manifest.capabilities.includes(capability))throw Object.assign(new Error(`Agent ${manifest.id} lacks capability ${capability}`),{code:"CONTROL_CAPABILITY_DENIED"})}
export function assertAgentAutonomy(manifest:PowerChainAgentManifest,required:AgentAutonomyLevel){if(manifest.maxAutonomyLevel<required)throw Object.assign(new Error(`Agent ${manifest.id} autonomy level ${manifest.maxAutonomyLevel} is below required level ${required}`),{code:"CONTROL_AUTONOMY_DENIED"})}
export function evaluateActionIntent(manifest:PowerChainAgentManifest,intent:ActionIntent):ControlPlaneDecision{const approvalKey={MARKETPLACE_TRADE:"marketplace.trade",TOKEN_ISSUANCE:"token.mint",TREASURY_TRANSFER:"treasury.transfer",DEVICE_COMMAND:"device.command",PREPARE_TRANSACTION:"transaction.prepare"}[intent.type];const prohibited=intent.type==="TREASURY_TRANSFER"||intent.type==="TOKEN_ISSUANCE"||intent.type==="MARKETPLACE_TRADE";return{allowed:!prohibited||manifest.maxAutonomyLevel>=2,requiresApproval:Boolean(approvalKey&&manifest.requiresApproval.includes(approvalKey))||prohibited,reasons:prohibited?["Consequential action remains outside direct agent authority."]:[],policyVersion:"1.0.0",intent}}
export const energyAgentManifest:PowerChainAgentManifest={id:"energy-agent",name:"Energy Analyst",version:"1.0.0",description:"Analyzes energy production, devices, forecasting and anomalies without direct wallet authority.",capabilities:["energy-analysis","forecasting","device-monitoring","anomaly-detection","revenue-analysis"],permissions:{read:["energy:*","devices:*","assets:*","telemetry:*","evidence:*"],write:["reports:*","alerts:*","tasks:*"],execute:[]},networks:{solana:true,sui:true},requiresApproval:["marketplace.trade","token.mint","treasury.transfer","device.command"],skills:["powerchain-energy-monitoring","powerchain-rwa-analysis","powerchain-device-health"],tools:["energy_get_summary","device_get_health","forecast_generation","report_prepare"],maxAutonomyLevel:2};

export * from "./agents";
