export const CONTROL_PLANE_VERSION="1.0.0" as const;
export type AgentAutonomyLevel=0|1|2|3|4|5;
export type AgentPermission="READ"|"ANALYZE"|"PREPARE"|"REQUEST_APPROVAL"|"EXECUTE_PREAUTHORIZED"|"AUTONOMOUS";
export interface PowerChainAgentManifest{id:string;name:string;version:"1.0.0";description:string;capabilities:string[];permissions:{read:string[];write:string[];execute:string[]};networks:{solana?:boolean;sui?:boolean};requiresApproval:string[];skills:string[];tools:string[];maxAutonomyLevel:AgentAutonomyLevel}
export type ActionIntentType="OPEN_ASSET"|"CREATE_ALERT"|"GENERATE_REPORT"|"CREATE_TASK"|"PREPARE_TRANSACTION"|"DEVICE_COMMAND"|"MARKETPLACE_TRADE"|"TOKEN_ISSUANCE"|"TREASURY_TRANSFER";
export interface ActionIntent{id:string;organizationId:string;actor:{type:"user"|"agent"|"service";id:string};type:ActionIntentType;resource?:{type:string;id:string};payload:Record<string,unknown>;requestId:string;traceId:string;correlationId:string;createdAt:string}
export interface ControlPlaneDecision{allowed:boolean;requiresApproval:boolean;reasons:string[];policyVersion:"1.0.0";intent:ActionIntent}
const levelPermissions:Record<AgentAutonomyLevel,AgentPermission[]>={0:["READ"],1:["READ","ANALYZE"],2:["READ","ANALYZE","PREPARE"],3:["READ","ANALYZE","PREPARE","REQUEST_APPROVAL"],4:["READ","ANALYZE","PREPARE","REQUEST_APPROVAL","EXECUTE_PREAUTHORIZED"],5:["READ","ANALYZE","PREPARE","REQUEST_APPROVAL","EXECUTE_PREAUTHORIZED","AUTONOMOUS"]};
export function permissionsForLevel(level:AgentAutonomyLevel){return [...levelPermissions[level]]}
export function evaluateActionIntent(manifest:PowerChainAgentManifest,intent:ActionIntent):ControlPlaneDecision{const consequential=new Set<ActionIntentType>(["DEVICE_COMMAND","MARKETPLACE_TRADE","TOKEN_ISSUANCE","TREASURY_TRANSFER","PREPARE_TRANSACTION"]);const requiresApproval=consequential.has(intent.type)||manifest.requiresApproval.includes(intent.type.toLowerCase());return{allowed:manifest.maxAutonomyLevel>=2||!consequential.has(intent.type),requiresApproval,reasons:requiresApproval?["Consequential action remains subject to PowerChain policy and explicit approval."]:[],policyVersion:"1.0.0",intent}}
export const energyAgentManifest:PowerChainAgentManifest={id:"energy-agent",name:"Energy Analyst",version:"1.0.0",description:"Analyzes energy, devices and renewable operations without wallet-signing authority.",capabilities:["energy-analysis","forecasting","device-monitoring","anomaly-detection","revenue-analysis"],permissions:{read:["energy:*","devices:*","assets:*","telemetry:*","evidence:*"],write:["reports:*","alerts:*","tasks:*"],execute:[]},networks:{solana:true,sui:true},requiresApproval:["marketplace_trade","token_issuance","treasury_transfer","device_command"],skills:["powerchain-energy-monitoring","powerchain-rwa-analysis","powerchain-device-health"],tools:["energy_get_summary","device_get_health","forecast_generation","report_prepare"],maxAutonomyLevel:2};
