import type{AiProviderConnection,GridLlmConfig}from"@powerchain/ai-core";
export interface AiGatewayRequest{requestId:string;userId:string;message:string;model:GridLlmConfig;provider?:AiProviderConnection;maxCostUsd?:string;systemPrompt?:string;signal?:AbortSignal}
export interface AiGatewayResponse{requestId:string;modelId:string;text:string;inputTokens:number;outputTokens:number;latencyMs:number;provider:string;executionMode:"provider"|"safe-fallback";errorCode?:string}
function providerFromEnvironment():AiProviderConnection|undefined{const baseUrl=process.env.POWERCHAIN_AI_BASE_URL?.trim();if(!baseUrl)return undefined;return{id:"server-provider",ownerId:"powerchain",name:process.env.POWERCHAIN_AI_PROVIDER_NAME?.trim()||"PowerChain Server Provider",protocol:(process.env.POWERCHAIN_AI_PROTOCOL?.trim()||"openai-compatible") as AiProviderConnection["protocol"],baseUrl,defaultModel:process.env.POWERCHAIN_AI_MODEL?.trim(),status:"active"}}
export function validateProviderConnection(connection:AiProviderConnection){let url:URL;try{url=new URL(connection.baseUrl)}catch{throw Object.assign(new Error("AI provider URL is invalid"),{code:"AI_PROVIDER_URL_INVALID"})}const local=["localhost","127.0.0.1","::1"].includes(url.hostname);if(connection.protocol==="local"){if(!local)throw Object.assign(new Error("Local AI providers must use a loopback host"),{code:"AI_PROVIDER_LOCALHOST_REQUIRED"});if(url.protocol!=="http:"&&url.protocol!=="https:")throw Object.assign(new Error("Local AI provider URL must use HTTP or HTTPS"),{code:"AI_PROVIDER_PROTOCOL_INVALID"})}else{if(url.protocol!=="https:")throw Object.assign(new Error("Remote AI provider URL must use HTTPS"),{code:"AI_PROVIDER_HTTPS_REQUIRED"});if(local)throw Object.assign(new Error("Remote AI providers cannot target loopback addresses"),{code:"AI_PROVIDER_PRIVATE_ENDPOINT"})}return url}
function fallback(input:AiGatewayRequest,started:number,provider:string,errorCode?:string):AiGatewayResponse{return{requestId:input.requestId,modelId:input.model.modelId,text:"PowerChain Copilot prepared the request, but live model execution requires a configured and reachable server-side language-model provider. No operational values, evidence, transactions, or settlement state have been invented.",inputTokens:Math.ceil(input.message.length/4),outputTokens:37,latencyMs:Date.now()-started,provider,executionMode:"safe-fallback",...(errorCode?{errorCode}:{})}}
export async function routeInference(input:AiGatewayRequest):Promise<AiGatewayResponse>{const started=Date.now();const connection=input.provider??providerFromEnvironment();if(!connection)return fallback(input,started,"PowerChain Safe Fallback","AI_PROVIDER_UNCONFIGURED");let base:URL;try{base=validateProviderConnection(connection)}catch(error){return fallback(input,started,connection.name,error&&typeof error==="object"&&"code" in error?String((error as{code?:unknown}).code):"AI_PROVIDER_INVALID")}
 if(connection.protocol!=="openai-compatible"&&connection.protocol!=="local")return fallback(input,started,connection.name,"AI_PROVIDER_PROTOCOL_UNSUPPORTED");
 const endpoint=new URL(base.toString());endpoint.pathname=`${endpoint.pathname.replace(/\/$/,"")}/chat/completions`.replace(/\/+/g,"/");
 const controller=new AbortController();const onAbort=()=>controller.abort();input.signal?.addEventListener("abort",onAbort,{once:true});const timeout=setTimeout(()=>controller.abort(),Number(process.env.POWERCHAIN_AI_TIMEOUT_MS??30_000));
 try{const apiKey=process.env.POWERCHAIN_AI_API_KEY?.trim();const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json",...(apiKey?{authorization:`Bearer ${apiKey}`}:{})},body:JSON.stringify({model:connection.defaultModel||input.model.modelId,messages:[{role:"system",content:input.systemPrompt??"You are PowerChain Copilot. Physical systems and auditable evidence are authoritative. Never invent telemetry, balances, prices, signatures, transactions, sources, or settlement state. Protected actions require policy and human approval."},{role:"user",content:input.message}],temperature:input.model.temperature,max_tokens:input.model.maxOutputTokens,stream:false}),signal:controller.signal,cache:"no-store"});if(!response.ok)return fallback(input,started,connection.name,`AI_PROVIDER_HTTP_${response.status}`);const body=await response.json() as Record<string,unknown>;const choices=Array.isArray(body.choices)?body.choices:[];const first=choices[0] as Record<string,unknown>|undefined;const message=first?.message as Record<string,unknown>|undefined;const text=typeof message?.content==="string"?message.content.trim():"";if(!text)return fallback(input,started,connection.name,"AI_PROVIDER_EMPTY_RESPONSE");const usage=(body.usage??{}) as Record<string,unknown>;return{requestId:input.requestId,modelId:connection.defaultModel||input.model.modelId,text,inputTokens:Number(usage.prompt_tokens??Math.ceil(input.message.length/4)),outputTokens:Number(usage.completion_tokens??Math.ceil(text.length/4)),latencyMs:Date.now()-started,provider:connection.name,executionMode:"provider"}}catch(error){return fallback(input,started,connection.name,controller.signal.aborted?"AI_PROVIDER_TIMEOUT":"AI_PROVIDER_UNAVAILABLE")}finally{clearTimeout(timeout);input.signal?.removeEventListener("abort",onAbort)}}
