import type { AcpCommand,AcpJob,AcpProposal,ApprovalEnvelope,CommandReceipt,ExecutionAttempt,ExecutionAuthorization,Money,ProviderSelectionStrategy } from "@powerchain/acp-contracts";
import { assertCommandTenant,assertExecutionNotAlreadyCompleted,assertKillSwitchOff,assertNoAutoSpend,assertSpendWithinLimit,assertSupportedAsset,deriveAllowedActions,transitionJob } from "@powerchain/acp-domain";
import { approvalService } from "@powerchain/approvals";
import { acpRepositories,canonicalHash,withAcpTransaction } from "@powerchain/database/acp";
import { AcpPolicyEngine,readProductionAcpConfig } from "@powerchain/policy";
import { acpExecutionWallet } from "@powerchain/wallets/acp";
import { acpAdapterGateway } from "../gateway/client";

const makeId=(prefix:string)=>`${prefix}_${crypto.randomUUID().replaceAll("-","")}`;
const publicId=(prefix:string)=>`${prefix}-${Math.floor(Date.now()/1000).toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;
const usdc=(raw:string):Money=>({asset:"USDC",rawAmount:raw,decimals:6,displayAmount:(Number(raw)/1_000_000).toFixed(2)});
const receipt=(command:AcpCommand,state:CommandReceipt["state"],extra:Partial<CommandReceipt>={}):CommandReceipt=>({commandId:command.id,requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,state,createdAt:new Date().toISOString(),...extra});
const text=(value:unknown,name:string)=>{if(typeof value!=="string"||!value.trim())throw Object.assign(new Error(`${name} is required`),{code:"ACP_VALIDATION_ERROR"});return value.trim()};
const integer=(value:unknown,name:string)=>{const number=Number(value);if(!Number.isInteger(number))throw Object.assign(new Error(`${name} must be an integer`),{code:"ACP_VALIDATION_ERROR"});return number};

export class AcpKernel{
  private readonly config=readProductionAcpConfig();private readonly policyEngine=new AcpPolicyEngine(this.config);
  async dispatch(command:AcpCommand):Promise<CommandReceipt|Record<string,unknown>>{
    if(command.type==="acp.provider.search")return this.searchProviders(command);
    return withAcpTransaction(command.organizationId,async tx=>{
      const context={organizationId:command.organizationId,transaction:tx};
      const replay=await acpRepositories.commands.findByIdempotencyKey(context,command.idempotencyKey);if(replay?.receipt)return replay.receipt;
      await acpRepositories.commands.save(context,command);
      let result:CommandReceipt;
      switch(command.type){
        case"acp.proposal.create":result=await this.createProposal(command,tx);break;
        case"acp.job.create":result=await this.createJobIntent(command,tx);break;
        case"acp.job.request_funding":result=await this.requestFunding(command,tx);break;
        case"acp.job.approve_funding":result=await this.authorizeFunding(command,tx);break;
        case"acp.job.request_completion":result=await this.requestCompletion(command,tx);break;
        case"acp.job.complete":result=await this.authorizeCompletion(command,tx);break;
        case"acp.deliverable.review":result=await this.reviewDeliverable(command,tx);break;
        case"acp.deliverable.request_revision":result=await this.requestRevision(command,tx);break;
        case"acp.job.reject":result=await this.rejectJob(command,tx);break;
        case"acp.job.reconcile":result=await this.requestReconciliation(command,tx);break;
        default:throw Object.assign(new Error(`Command ${command.type} is not implemented by the production kernel`),{code:"ACP_COMMAND_UNSUPPORTED"});
      }
      await acpRepositories.commands.saveReceipt(context,command.id,result);
      return result;
    });
  }
  private async searchProviders(command:AcpCommand){
    const payload=command.payload as Record<string,unknown>;const capabilityId=text(payload.capabilityId,"capabilityId"),query=text(payload.query??capabilityId,"query");const policy=await this.policyEngine.evaluate(command);assertNoAutoSpend(policy);
    let providers;let source:"live"|"cache"="live";let stale=false;
    try{providers=await acpAdapterGateway.discoverProviders({organizationId:command.organizationId,query,capabilityId,allowedChains:policy.allowedChains,topK:Math.max(1,Math.min(Number(payload.topK??10),25))});await acpRepositories.providers.replace({organizationId:command.organizationId},capabilityId,providers,300)}catch(error){if(!this.config.providerCacheFallback)throw error;const cached=await acpRepositories.providers.get({organizationId:command.organizationId},capabilityId,{allowStale:true});if(!cached.providers.length)throw error;providers=cached.providers;source="cache";stale=cached.stale}
    return{commandId:command.id,requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,source,stale,providers,policyHash:policy.hash};
  }
  private async createProposal(command:AcpCommand,tx:any){
    const payload=command.payload as Record<string,unknown>;const maximumBudget=usdc(text(payload.maximumBudgetRaw,"maximumBudgetRaw"));assertSupportedAsset(maximumBudget.asset);const chainId=integer(payload.chainId,"chainId");const requirements=(payload.requirements&&typeof payload.requirements==="object"?payload.requirements:{}) as Record<string,unknown>;
    const proposal:AcpProposal={id:makeId("prp"),publicId:publicId("ACP-P"),organizationId:command.organizationId,capabilityId:text(payload.capabilityId,"capabilityId"),providerId:text(payload.providerId,"providerId"),providerIdentityHash:text(payload.providerIdentityHash,"providerIdentityHash"),chainId,offeringName:text(payload.offeringName,"offeringName"),requirements,requirementsHash:canonicalHash(requirements),maximumBudget,strategy:(payload.strategy??"balanced") as ProviderSelectionStrategy,status:"pending_approval",version:1,createdBy:command.actor.id,createdAt:command.createdAt,updatedAt:command.createdAt};
    const policy=await this.policyEngine.evaluate(command,undefined,tx);assertNoAutoSpend(policy);assertKillSwitchOff(this.config.killSwitch);assertSpendWithinLimit(maximumBudget,policy.maxJobAmount);const saved=await acpRepositories.proposals.create({organizationId:command.organizationId,transaction:tx},proposal);const approval=await approvalService.requestForProposal({organizationId:command.organizationId,proposal:saved,policy,transaction:tx});await acpRepositories.outbox.append({organizationId:command.organizationId,transaction:tx},{topic:"powerchain.acp.proposal.created.v1",aggregateType:"AcpProposal",aggregateId:saved.id,payload:{proposal:saved,approvalId:approval.id},requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,causationId:command.causationId});await acpRepositories.audit.append({organizationId:command.organizationId,transaction:tx},{actorType:command.actor.type,actorId:command.actor.id,action:"acp.proposal.create",resourceType:"AcpProposal",resourceId:saved.id,metadata:{approvalId:approval.id,policyHash:policy.hash},requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,causationId:command.causationId});return receipt(command,"pending_approval",{resourceId:saved.id,approvalId:approval.id});
  }
  private async createJobIntent(command:AcpCommand,tx:any){
    const payload=command.payload as Record<string,unknown>;const proposalId=text(payload.proposalId,"proposalId"),approvalId=text(payload.approvalId,"approvalId");const context={organizationId:command.organizationId,transaction:tx};const proposal=await acpRepositories.proposals.find(context,proposalId,true);if(!proposal)throw Object.assign(new Error("ACP proposal not found"),{code:"ACP_PROPOSAL_NOT_FOUND"});const policy=await this.policyEngine.evaluate(command,undefined,tx);assertNoAutoSpend(policy);assertKillSwitchOff(this.config.killSwitch);await approvalService.consumeProposalExact({organizationId:command.organizationId,approvalId,proposal,policyHash:policy.hash,transaction:tx});
    const job:AcpJob={id:makeId("acj"),publicId:publicId("ACP"),organizationId:command.organizationId,proposalId:proposal.id,providerId:proposal.providerId,providerIdentityHash:proposal.providerIdentityHash,chainId:proposal.chainId,capabilityId:proposal.capabilityId,offeringName:proposal.offeringName,requirements:proposal.requirements,requirementsHash:proposal.requirementsHash,requirementsVersion:1,requirementsLocked:false,state:"creating",approvedBudget:proposal.maximumBudget,reservedBudget:usdc("0"),actualSpend:usdc("0"),version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const saved=await acpRepositories.jobs.create(context,job);const authorization:ExecutionAuthorization={id:makeId("exa"),organizationId:command.organizationId,jobId:saved.id,action:"create_job",approvalId,providerIdentityHash:saved.providerIdentityHash,chainId:saved.chainId,requirementsHash:saved.requirementsHash,policySnapshotHash:policy.hash,resourceVersion:saved.version,expiresAt:new Date(Date.now()+15*60_000).toISOString(),createdAt:new Date().toISOString()};await acpRepositories.authorizations.create(context,authorization);const attempt=await acpRepositories.attempts.create(context,{organizationId:command.organizationId,jobId:saved.id,operation:"create_job",authorizationId:authorization.id,idempotencyKey:`${command.idempotencyKey}:execute`,status:"created",requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,...(command.causationId?{causationId:command.causationId}:{})});await this.queueExecution(context,command,saved,attempt,authorization);const updatedProposal={...proposal,status:"converted" as const,version:proposal.version+1,updatedAt:new Date().toISOString()};await acpRepositories.proposals.save(context,updatedProposal,proposal.version);return receipt(command,"executing",{resourceId:saved.id,executionAttemptId:attempt.id});
  }
  private async requestFunding(command:AcpCommand,tx:any){const payload=command.payload as Record<string,unknown>,jobId=text(payload.jobId,"jobId"),amount=usdc(text(payload.amountRaw,"amountRaw"));const context={organizationId:command.organizationId,transaction:tx};const job=await acpRepositories.jobs.lock(context,jobId);if(!job)throw Object.assign(new Error("ACP job not found"),{code:"ACP_JOB_NOT_FOUND"});assertCommandTenant(command,job);const policy=await this.policyEngine.evaluate(command,job,tx);assertNoAutoSpend(policy);assertSpendWithinLimit(amount,job.approvedBudget);const moved=transitionJob(job,"pending_funding_approval");const saved=await acpRepositories.jobs.save(context,moved,job.version);const approval=await approvalService.requestForJob({organizationId:command.organizationId,job:saved,action:"fund_job",proposalHash:job.proposalId,policy,amount,transaction:tx});await acpRepositories.outbox.append(context,{topic:"powerchain.acp.approval.requested.v1",aggregateType:"AcpJob",aggregateId:job.id,payload:{approvalId:approval.id,action:"fund_job",amount},requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,causationId:command.causationId});return receipt(command,"pending_approval",{resourceId:job.id,approvalId:approval.id})}
  private async authorizeFunding(command:AcpCommand,tx:any){const payload=command.payload as Record<string,unknown>,jobId=text(payload.jobId,"jobId"),approvalId=text(payload.approvalId,"approvalId");const context={organizationId:command.organizationId,transaction:tx};let job=await acpRepositories.jobs.lock(context,jobId);if(!job)throw Object.assign(new Error("ACP job not found"),{code:"ACP_JOB_NOT_FOUND"});const approval=await acpRepositories.approvals.find(context,approvalId,true);if(!approval)throw Object.assign(new Error("ACP approval not found"),{code:"ACP_APPROVAL_NOT_FOUND"});const amount=approval.amount;const policy=await this.policyEngine.evaluate(command,job,tx);assertKillSwitchOff(this.config.killSwitch);assertNoAutoSpend(policy);assertSpendWithinLimit(amount,job.approvedBudget);const attempts=await acpRepositories.attempts.listForJob(context,job.id);assertExecutionNotAlreadyCompleted(attempts.filter(attempt=>attempt.operation==="fund_job"));const account=await acpExecutionWallet.getExecutionAccount(command.organizationId,job.chainId);await acpExecutionWallet.assertSpendAllowed({organizationId:command.organizationId,accountId:account.id,chainId:job.chainId,asset:"USDC",amountRaw:amount.rawAmount,businessReference:`ACP:FUND:${command.organizationId}:${job.id}`});await approvalService.consumeJobExact({organizationId:command.organizationId,approvalId,job,policyHash:policy.hash,action:"fund_job",amount,transaction:tx});job=transitionJob(job,"funding_authorized");job.reservedBudget=amount;job=await acpRepositories.jobs.save(context,job,job.version-1);const authorization:ExecutionAuthorization={id:makeId("exa"),organizationId:command.organizationId,jobId:job.id,action:"fund_job",approvalId,providerIdentityHash:job.providerIdentityHash,chainId:job.chainId,amount,requirementsHash:job.requirementsHash,policySnapshotHash:policy.hash,resourceVersion:job.version,expiresAt:new Date(Date.now()+15*60_000).toISOString(),createdAt:new Date().toISOString()};await acpRepositories.authorizations.create(context,authorization);await acpRepositories.reservations.create(context,{jobId:job.id,authorizationId:authorization.id,amount,expiresAt:new Date(Date.now()+30*60_000).toISOString()});job=transitionJob(job,"funding");job=await acpRepositories.jobs.save(context,job,job.version-1);const attempt=await acpRepositories.attempts.create(context,{organizationId:command.organizationId,jobId:job.id,operation:"fund_job",authorizationId:authorization.id,idempotencyKey:`${command.idempotencyKey}:execute`,status:"created",requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,...(command.causationId?{causationId:command.causationId}:{})});await this.queueExecution(context,command,job,attempt,authorization);return receipt(command,"executing",{resourceId:job.id,executionAttemptId:attempt.id})}
  private async requestCompletion(command:AcpCommand,tx:any){const payload=command.payload as Record<string,unknown>,jobId=text(payload.jobId,"jobId");const context={organizationId:command.organizationId,transaction:tx};const job=await acpRepositories.jobs.lock(context,jobId);if(!job)throw Object.assign(new Error("ACP job not found"),{code:"ACP_JOB_NOT_FOUND"});const policy=await this.policyEngine.evaluate(command,job,tx);const moved=transitionJob(job,"pending_completion_approval");const saved=await acpRepositories.jobs.save(context,moved,job.version);const approval=await approvalService.requestForJob({organizationId:command.organizationId,job:saved,action:"complete_job",proposalHash:job.proposalId,policy,transaction:tx});return receipt(command,"pending_approval",{resourceId:job.id,approvalId:approval.id})}
  private async authorizeCompletion(command:AcpCommand,tx:any){const payload=command.payload as Record<string,unknown>,jobId=text(payload.jobId,"jobId"),approvalId=text(payload.approvalId,"approvalId");const context={organizationId:command.organizationId,transaction:tx};let job=await acpRepositories.jobs.lock(context,jobId);if(!job)throw Object.assign(new Error("ACP job not found"),{code:"ACP_JOB_NOT_FOUND"});const policy=await this.policyEngine.evaluate(command,job,tx);assertKillSwitchOff(this.config.killSwitch);await approvalService.consumeJobExact({organizationId:command.organizationId,approvalId,job,policyHash:policy.hash,action:"complete_job",transaction:tx});job=transitionJob(job,"completion_authorized");job=await acpRepositories.jobs.save(context,job,job.version-1);const authorization:ExecutionAuthorization={id:makeId("exa"),organizationId:command.organizationId,jobId:job.id,action:"complete_job",approvalId,providerIdentityHash:job.providerIdentityHash,chainId:job.chainId,requirementsHash:job.requirementsHash,policySnapshotHash:policy.hash,resourceVersion:job.version,expiresAt:new Date(Date.now()+15*60_000).toISOString(),createdAt:new Date().toISOString()};await acpRepositories.authorizations.create(context,authorization);job=transitionJob(job,"completing");job=await acpRepositories.jobs.save(context,job,job.version-1);const attempt=await acpRepositories.attempts.create(context,{organizationId:command.organizationId,jobId:job.id,operation:"complete_job",authorizationId:authorization.id,idempotencyKey:`${command.idempotencyKey}:execute`,status:"created",requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,...(command.causationId?{causationId:command.causationId}:{})});await this.queueExecution(context,command,job,attempt,authorization);return receipt(command,"executing",{resourceId:job.id,executionAttemptId:attempt.id})}
  private async reviewDeliverable(command:AcpCommand,tx:any){const payload=command.payload as Record<string,unknown>,jobId=text(payload.jobId,"jobId"),decision=text(payload.decision,"decision");if(!["accept","revision","dispute"].includes(decision))throw Object.assign(new Error("Deliverable review decision must be accept, revision, or dispute"),{code:"ACP_VALIDATION_ERROR"});const context={organizationId:command.organizationId,transaction:tx};const job=await acpRepositories.jobs.lock(context,jobId);if(!job)throw Object.assign(new Error("ACP job not found"),{code:"ACP_JOB_NOT_FOUND"});let next=job;if(decision==="revision")next=transitionJob(job,"revision_requested");if(decision==="dispute")next=transitionJob(job,"disputed");if(next!==job)await acpRepositories.jobs.save(context,next,job.version);await acpRepositories.audit.append(context,{actorType:command.actor.type,actorId:command.actor.id,action:`acp.deliverable.review.${decision}`,resourceType:"AcpJob",resourceId:job.id,reason:typeof payload.reason==="string"?payload.reason:undefined,metadata:{decision},requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,causationId:command.causationId});return receipt(command,"completed",{resourceId:job.id})}
  private async requestRevision(command:AcpCommand,tx:any){const payload=command.payload as Record<string,unknown>,jobId=text(payload.jobId,"jobId");const context={organizationId:command.organizationId,transaction:tx};const job=await acpRepositories.jobs.lock(context,jobId);if(!job)throw Object.assign(new Error("ACP job not found"),{code:"ACP_JOB_NOT_FOUND"});const moved=transitionJob(job,"revision_requested");await acpRepositories.jobs.save(context,moved,job.version);await acpRepositories.outbox.append(context,{topic:"powerchain.acp.revision.requested.v1",aggregateType:"AcpJob",aggregateId:job.id,payload:{reason:text(payload.reason??"Revision requested","reason")},requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,causationId:command.causationId});return receipt(command,"completed",{resourceId:job.id})}
  private async rejectJob(command:AcpCommand,tx:any){const payload=command.payload as Record<string,unknown>,jobId=text(payload.jobId,"jobId");const context={organizationId:command.organizationId,transaction:tx};const job=await acpRepositories.jobs.lock(context,jobId);if(!job)throw Object.assign(new Error("ACP job not found"),{code:"ACP_JOB_NOT_FOUND"});const moved=transitionJob(job,"rejected");await acpRepositories.jobs.save(context,moved,job.version);return receipt(command,"completed",{resourceId:job.id})}
  private async requestReconciliation(command:AcpCommand,tx:any){const payload=command.payload as Record<string,unknown>,jobId=text(payload.jobId,"jobId");const context={organizationId:command.organizationId,transaction:tx};const job=await acpRepositories.jobs.lock(context,jobId);if(!job)throw Object.assign(new Error("ACP job not found"),{code:"ACP_JOB_NOT_FOUND"});const next=job.state==="reconciling"?job:transitionJob(job,"reconciling");if(next!==job)await acpRepositories.jobs.save(context,next,job.version);await acpRepositories.outbox.append(context,{topic:"powerchain.acp.reconciliation.requested.v1",aggregateType:"AcpJob",aggregateId:job.id,payload:{jobId:job.id},requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,causationId:command.causationId});return receipt(command,"accepted",{resourceId:job.id})}
  private async queueExecution(context:any,command:AcpCommand,job:AcpJob,attempt:ExecutionAttempt,authorization:ExecutionAuthorization){await acpRepositories.outbox.append(context,{topic:"powerchain.acp.execution.requested.v1",aggregateType:"AcpExecutionAttempt",aggregateId:attempt.id,payload:{organizationId:command.organizationId,jobId:job.id,attemptId:attempt.id,authorization,job:{id:job.id,externalJobId:job.externalJobId,chainId:job.chainId,offeringName:job.offeringName,providerId:job.providerId,requirements:job.requirements,approvedBudget:job.approvedBudget},evaluatorAddress:process.env.POWERCHAIN_ACP_EVALUATOR_ADDRESS??""},requestId:command.requestId,traceId:command.traceId,correlationId:command.correlationId,causationId:command.causationId})}
  async recordApprovalRejection(input:{organizationId:string;approval:ApprovalEnvelope;actorId:string;requestId:string;traceId:string;correlationId:string}){
    return withAcpTransaction(input.organizationId,async tx=>{
      const context={organizationId:input.organizationId,transaction:tx};
      if(input.approval.resourceType==="proposal"){
        const proposal=await acpRepositories.proposals.find(context,input.approval.resourceId,true);
        if(proposal&&proposal.status!=="rejected"){
          await acpRepositories.proposals.save(context,{...proposal,status:"rejected",version:proposal.version+1,updatedAt:new Date().toISOString()},proposal.version);
        }
      }else if(input.approval.resourceType==="job"&&input.approval.jobId){
        const job=await acpRepositories.jobs.lock(context,input.approval.jobId);
        if(job){
          let next=job;
          if(input.approval.action==="fund_job"&&job.state==="pending_funding_approval")next=transitionJob(job,"created");
          if(input.approval.action==="complete_job"&&job.state==="pending_completion_approval")next=transitionJob(job,"submitted");
          if(next!==job)await acpRepositories.jobs.save(context,next,job.version);
        }
      }
      await acpRepositories.audit.append(context,{actorType:"user",actorId:input.actorId,action:"acp.approval.rejected",resourceType:input.approval.resourceType,resourceId:input.approval.resourceId,metadata:{approvalId:input.approval.id,action:input.approval.action},requestId:input.requestId,traceId:input.traceId,correlationId:input.correlationId});
      await acpRepositories.outbox.append(context,{topic:"powerchain.acp.approval.rejected.v1",aggregateType:"ApprovalEnvelope",aggregateId:input.approval.id,payload:{approvalId:input.approval.id,resourceType:input.approval.resourceType,resourceId:input.approval.resourceId,action:input.approval.action},requestId:input.requestId,traceId:input.traceId,correlationId:input.correlationId});
      return input.approval;
    });
  }
  async job(organizationId:string,jobId:string){const job=await acpRepositories.jobs.find({organizationId},jobId);return job?{...job,allowedActions:deriveAllowedActions(job)}:null}
  async jobs(organizationId:string,states?:string[]){return (await acpRepositories.jobs.list({organizationId},{states})).map(job=>({...job,allowedActions:deriveAllowedActions(job)}))}
  async proposals(organizationId:string){return acpRepositories.proposals.list({organizationId})}
  async approvals(organizationId:string){return acpRepositories.approvals.pending({organizationId})}
}
export const acpKernel=new AcpKernel();
