import type { AcpJob,AcpReconciliationOutcome,ExecutionAttempt,ExecutionReceipt } from "@powerchain/acp-contracts";
import { transitionJob } from "@powerchain/acp-domain";
import { acpRepositories,withAcpTransaction } from "@powerchain/database/acp";
import { acpLedger } from "@powerchain/ledger";
import { acpExecutionWallet } from "@powerchain/wallets/acp";
import { acpAdapterGateway } from "../gateway/client";

export class AcpReconciliationService{
  async reconcileJob(organizationId:string,jobId:string):Promise<{outcome:AcpReconciliationOutcome;job:AcpJob;receipt?:ExecutionReceipt;message:string}>{
    const job=await acpRepositories.jobs.find({organizationId},jobId);if(!job)throw Object.assign(new Error("ACP job not found"),{code:"ACP_JOB_NOT_FOUND"});if(!job.externalJobId)return{outcome:"execution_not_found",job,message:"No external job reference has been confirmed yet"};
    const external=await acpAdapterGateway.getJob({organizationId,providerId:job.providerId,chainId:job.chainId,externalJobId:job.externalJobId});const attempts=await acpRepositories.attempts.listForJob({organizationId},job.id);const unknown=attempts.find(attempt=>attempt.status==="unknown");
    if(!unknown){const desired=this.mapExternalStatus(job,external.status);if(desired===job.state){await this.touch(job);return{outcome:"synchronized",job:{...job,lastReconciledAt:new Date().toISOString()},message:"Local and external ACP lifecycle state are synchronized"}}if(desired&&this.nonFinancialRepairAllowed(job.state,desired)){const repaired=await this.repairState(job,desired);return{outcome:"repaired_non_financial",job:repaired,message:`Non-financial state repaired to ${desired}`}}return{outcome:"conflict",job,message:`External state ${external.status} does not match local state ${job.state}`}}
    const outcome=await this.resolveUnknown(job,unknown,external.status);return outcome;
  }
  private mapExternalStatus(job:AcpJob,status:string):AcpJob["state"]|undefined{if(status==="funded")return"funded";if(status==="submitted")return"submitted";if(status==="completed")return"completed";if(status==="rejected")return"rejected";if(status==="expired")return"expired";if(status==="open"||status==="budget_set")return job.externalJobId?"created":undefined;return undefined}
  private nonFinancialRepairAllowed(from:AcpJob["state"],to:AcpJob["state"]){return !["funding","execution_unknown","funded","completed","reconciliation_conflict"].includes(from)&&!["funded","completed"].includes(to)}
  private async touch(job:AcpJob){await withAcpTransaction(job.organizationId,async tx=>{const locked=await acpRepositories.jobs.lock({organizationId:job.organizationId,transaction:tx},job.id);if(!locked)return;await acpRepositories.jobs.save({organizationId:job.organizationId,transaction:tx},{...locked,lastReconciledAt:new Date().toISOString(),version:locked.version+1,updatedAt:new Date().toISOString()},locked.version)})}
  private async repairState(job:AcpJob,state:AcpJob["state"]){return withAcpTransaction(job.organizationId,async tx=>{const context={organizationId:job.organizationId,transaction:tx};const locked=await acpRepositories.jobs.lock(context,job.id);if(!locked)throw new Error("ACP_JOB_NOT_FOUND");const repaired={...locked,state,lastReconciledAt:new Date().toISOString(),version:locked.version+1,updatedAt:new Date().toISOString()};return acpRepositories.jobs.save(context,repaired,locked.version)})}
  private async resolveUnknown(job:AcpJob,attempt:ExecutionAttempt,externalStatus:string){
    const operation=attempt.operation;const confirmed=operation==="fund_job"?['funded','submitted','completed'].includes(externalStatus):operation==="complete_job"?externalStatus==='completed':operation==="reject_job"?externalStatus==='rejected':operation==="create_job"?externalStatus!=="unknown":false;
    if(!confirmed&&externalStatus==="unknown")return{outcome:"still_unknown" as const,job,message:"External ACP state remains ambiguous; duplicate execution stays blocked"};
    if(!confirmed){await acpRepositories.attempts.updateStatus({organizationId:job.organizationId},attempt.id,"reconciled",{errorCode:"EXECUTION_NOT_FOUND"});return{outcome:"execution_not_found" as const,job,message:"External ACP state does not show the ambiguous operation as confirmed"}}
    if(operation==="fund_job"){
      const account=await acpExecutionWallet.getExecutionAccount(job.organizationId,job.chainId);const wallet=await acpExecutionWallet.reconcile(account.id);const expected=BigInt(job.reservedBudget.rawAmount);const matches=wallet.observedTransactions.filter(transaction=>transaction.confirmed&&transaction.asset==="USDC"&&BigInt(transaction.amountRaw)===expected);if(matches.length!==1){await acpRepositories.incidents.create({organizationId:job.organizationId},{jobId:job.id,severity:"high",type:"financial_reconciliation",status:"contained",title:"ACP funding reconciliation mismatch",description:`Expected one confirmed ${expected} raw USDC wallet transaction; observed ${matches.length}`,metadata:{wallet}});await this.repairState(job,"reconciliation_conflict");return{outcome:"financial_difference" as const,job,message:"External funding appears confirmed but wallet evidence is not uniquely reconcilable"}}
      const transaction=matches[0]!;const receipt=await acpRepositories.receipts.create({organizationId:job.organizationId},{organizationId:job.organizationId,jobId:job.id,attemptId:attempt.id,operation,externalJobId:job.externalJobId!,transactionReference:transaction.reference,status:"confirmed",principal:{asset:"USDC",rawAmount:transaction.amountRaw,decimals:6},...(transaction.networkFeeRaw?{networkFee:{asset:"USDC",rawAmount:transaction.networkFeeRaw,decimals:6}}:{}),requestId:attempt.requestId,traceId:attempt.traceId,correlationId:attempt.correlationId,causationId:attempt.causationId});await acpLedger.confirmFunding({organizationId:job.organizationId,jobId:job.id,attemptId:attempt.id,receiptId:receipt.id,authorizationId:attempt.authorizationId,principalRaw:transaction.amountRaw,networkFeeRaw:transaction.networkFeeRaw});await acpRepositories.attempts.updateStatus({organizationId:job.organizationId},attempt.id,"reconciled",{externalReference:transaction.reference});const updated=await withAcpTransaction(job.organizationId,async tx=>{const context={organizationId:job.organizationId,transaction:tx};const locked=await acpRepositories.jobs.lock(context,job.id);if(!locked)throw new Error("ACP_JOB_NOT_FOUND");const value={...locked,state:"funded" as const,requirementsLocked:true,actualSpend:{asset:"USDC" as const,rawAmount:transaction.amountRaw,decimals:6 as const},lastReconciledAt:new Date().toISOString(),version:locked.version+1,updatedAt:new Date().toISOString()};await acpRepositories.reservations.consume(context,attempt.authorizationId);return acpRepositories.jobs.save(context,value,locked.version)});return{outcome:"execution_confirmed" as const,job:updated,receipt,message:"Funding confirmed by external ACP state and restricted-wallet evidence"};
    }
    const receipt=await acpRepositories.receipts.create({organizationId:job.organizationId},{organizationId:job.organizationId,jobId:job.id,attemptId:attempt.id,operation,externalJobId:job.externalJobId!,status:"confirmed",requestId:attempt.requestId,traceId:attempt.traceId,correlationId:attempt.correlationId,causationId:attempt.causationId});await acpRepositories.attempts.updateStatus({organizationId:job.organizationId},attempt.id,"reconciled");const desired=operation==="complete_job"?"completed":operation==="reject_job"?"rejected":"created";const updated=await this.repairState(job,desired);return{outcome:"execution_confirmed" as const,job:updated,receipt,message:`${operation} confirmed by external ACP state`};
  }
}
export const acpReconciliation=new AcpReconciliationService();
