"use client";
import { useEffect,useState } from "react";
import type { ReactNode } from "react";
import Link from "next/link";
import { Coins, LockKeyhole, ReceiptText, ShieldCheck } from "lucide-react";
import { SettingsLayout } from "@/components/profile/settings-layout";

type Credits={account:{availableBaseUnits:string;reservedBaseUnits:string;spentBaseUnits:string;availablePwrc:string;reservedPwrc:string;spentPwrc:string};pricing:{messageUnits:1;pwrc:"10000";baseUnits:"10000000000000";referenceValueUsd:"0.020000";onchainPerMessage:false}};
export default function CreditsPage(){const[data,setData]=useState<Credits|null>(null),[error,setError]=useState<string|null>(null);useEffect(()=>{void fetch("/api/v1/chat/credits",{cache:"no-store"}).then(async response=>{const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message??"Credits unavailable");setData(body.data)}).catch(cause=>setError(cause instanceof Error?cause.message:"Credits unavailable"))},[]);return <SettingsLayout title="PWRC / Copilot Credits" subtitle="Copilot chat uses a reserved internal PWRC credit ledger so each response can settle deterministically without one Solana transfer per turn.">
 <div className="grid gap-4 lg:grid-cols-3"><Metric label="Available" value={`${data?.account.availablePwrc??"—"} PWRC`}/><Metric label="Reserved" value={`${data?.account.reservedPwrc??"—"} PWRC`}/><Metric label="Spent" value={`${data?.account.spentPwrc??"—"} PWRC`}/></div>
 {error&&<div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/[.06] p-4 text-sm text-amber-800 dark:text-amber-200">{error}</div>}
 <section className="panel mt-5 p-5"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-900 text-white"><Coins className="h-5 w-5"/></span><div><h2 className="font-semibold">Canonical message unit</h2><p className="mt-1 text-sm text-[var(--muted)]">1 completed response = 1 MSG UNIT = 10,000 PWRC = 10,000,000,000,000 base units · $0.020 reference value.</p></div></div><div className="mt-4 flex flex-wrap gap-2"><Link href="/checkout?asset=PWRC&purpose=copilot-credits" className="pc-button primary">Buy PWRC / Credits</Link><Link href="/chat" className="pc-button framed">Open Copilot Chat</Link></div></section>
 <section className="mt-4 grid gap-3 md:grid-cols-3"><Info icon={<LockKeyhole/>} title="Reserve first" text="Credits are reserved before model generation and released when delivery fails or is cancelled."/><Info icon={<ReceiptText/>} title="Settle once" text="A completed response atomically moves reserved PWRC to spent and appends a receipt-linked ledger entry."/><Info icon={<ShieldCheck/>} title="Tokenized proof" text="The proof is non-transferable and is not a minted asset, NFT, security, or financial instrument."/></section>
 </SettingsLayout>}
function Metric({label,value}:{label:string;value:string}){return <div className="panel p-4"><p className="text-xs font-semibold uppercase tracking-wider text-[var(--muted)]">{label}</p><strong className="mt-2 block text-xl tabular-nums">{value}</strong></div>}
function Info({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <article className="panel p-4"><span className="text-emerald-800 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><strong className="mt-3 block text-sm">{title}</strong><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{text}</p></article>}
