"use client";
import Link from "next/link";
import { Coins,CreditCard,Database,ExternalLink,RefreshCw,ShieldCheck } from "lucide-react";
import { SettingsLayout } from "@/components/profile/settings-layout";
import { useCopilotCredits } from "@/hooks/use-copilot-credits";
import type { CopilotDisplayCurrency } from "@powerchain/credits/types";
const currencies:CopilotDisplayCurrency[]=["USD","EUR","SOL","PWRC"];
export default function CopilotCreditsSettings(){
 const credits=useCopilotCredits();
 const q=credits.quote;
 return <SettingsLayout title="PWRC / Copilot Credits" subtitle="Fund fast internal Copilot usage with PWRC without creating one Solana transaction per chat message.">
  <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
   <section className="panel p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Available Copilot balance</p><h2 className="mt-2 text-3xl font-bold tabular-nums">{credits.loading?"…":`${credits.account?.availablePwrc??"0"} PWRC`}</h2><p className="mt-2 text-sm text-[var(--muted)]">Reserved: {credits.account?.reservedPwrc??"0"} PWRC · Total: {credits.account?.balancePwrc??"0"} PWRC</p></div><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-950 text-white"><Coins className="h-5 w-5"/></span></div><div className="mt-5 flex flex-wrap gap-2"><Link href="/checkout?asset=PWRC&purpose=copilot-credits" className="pc-button primary"><CreditCard/>Buy PWRC / Credits</Link><button type="button" className="pc-button framed" onClick={()=>void credits.refresh()}><RefreshCw/>Refresh balance</button></div>{credits.error&&<p className="mt-4 text-sm text-amber-700">{credits.error}</p>}</section>
   <section className="panel p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Message quote</p><h2 className="mt-1 text-lg font-semibold">USD reference with sourced display conversion</h2></div><select aria-label="Display currency" className="h-10 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 text-sm" value={credits.currency} onChange={e=>credits.setCurrency(e.target.value as CopilotDisplayCurrency)}>{currencies.map(currency=><option key={currency}>{currency}</option>)}</select></div><div className="mt-4 divide-y divide-[var(--border)]"><Price label="Base message" usd="$0.020" pwrc="10,000 PWRC"/><Price label="Real-data message" usd="$0.015" pwrc="7,500 PWRC"/><Price label="PWRC reference" usd="$0.000002" pwrc="per PWRC"/></div><div className="mt-4 rounded-xl border border-[var(--border)] p-3"><span className="text-xs text-[var(--muted)]">Current base quote</span><strong className="mt-1 block text-lg tabular-nums">{q?.displayAmount?`${q.displayAmount} ${q.displayCurrency}`:"Rate unavailable"}</strong><small className="mt-1 block text-[var(--muted)]">{q?.solUsdPrice?`SOL/USD ${q.solUsdPrice} · `:""}{q?.eurUsdPrice?`EUR/USD ${q.eurUsdPrice}`:""}</small></div></section>
  </div>
  <section className="panel p-5 sm:p-6"><h2 className="text-lg font-bold">How credits work</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><Step icon={<Coins/>} title="Fund" text="Confirmed PWRC funding credits the internal ledger."/><Step icon={<ShieldCheck/>} title="Reserve" text="Credits are reserved before model generation."/><Step icon={<Database/>} title="Settle" text="Completed usage is settled against the immutable credit ledger."/><Step icon={<ExternalLink/>} title="Release" text="Unused reserved capacity is released; no per-message refund transaction is required."/></div><p className="mt-4 text-xs text-[var(--muted)]">USD is canonical pricing. EUR and SOL are informational display conversions shown only when sourced from Pyth, Jupiter, or explicit operator configuration.</p></section>
 </SettingsLayout>
}
function Price({label,usd,pwrc}:{label:string;usd:string;pwrc:string}){return <div className="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0"><span className="text-sm font-semibold">{label}</span><span className="text-right"><strong className="block tabular-nums">{usd}</strong><small className="text-[var(--muted)]">{pwrc}</small></span></div>}
function Step({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="rounded-2xl border border-[var(--border)] p-4"><span className="text-emerald-700 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><strong className="mt-3 block text-sm">{title}</strong><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{text}</p></article>}
