export const TOKEN_FRAMEWORK_VERSION="1.0.0" as const;
export const SOLANA_PROGRAM_IDS={system:"11111111111111111111111111111111",splToken:"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",token2022:"TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb",associatedToken:"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",metaplexTokenMetadata:"metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"} as const;
export type SolanaTokenStandard="SPL"|"TOKEN_2022";
export interface TokenMetadata{name:string;symbol:string;description:string;uri?:string;decimals:number}
export interface PowerChainTokenDefinition{id:"PWRC"|"PCT"|"CCT"|"ENERGY_CREDIT";version:"1.0.0";standard:SolanaTokenStandard|"SUI";purpose:string;metadata:TokenMetadata;programId?:string;mint?:string;deploymentState:"DEPLOYED"|"CONFIG_REQUIRED"|"PLANNED"}
export const CCT_TOKEN:PowerChainTokenDefinition={id:"CCT",version:"1.0.0",standard:"TOKEN_2022",purpose:"PowerChain Carbon Credit Token representing verified carbon attributes; issuance and retirement require evidence and policy approval.",metadata:{name:"PowerChain Carbon Credit Token",symbol:"CCT",description:"Verified carbon attribute token",decimals:9},deploymentState:"CONFIG_REQUIRED"};
export interface CarbonCreditEvidence{projectId:string;methodology:string;vintage:number;quantityGramsCo2e:bigint;evidenceIds:string[];verifier:string;verifiedAt:string}
export interface TokenIssuanceIntent{id:string;organizationId:string;tokenId:PowerChainTokenDefinition["id"];amountRaw:bigint;recipient:string;evidenceIds:string[];metadataUri?:string;requiresApproval:true;network:"solana"|"sui";createdAt:string}
export function createCctIssuanceIntent(input:{organizationId:string;recipient:string;amountRaw:bigint;evidence:CarbonCreditEvidence;metadataUri?:string}):TokenIssuanceIntent{if(input.amountRaw<=0n)throw new Error("CCT issuance amount must be positive");if(!input.evidence.evidenceIds.length||!input.evidence.verifier)throw new Error("Verified carbon evidence is required");return{id:`ccti_${crypto.randomUUID()}`,organizationId:input.organizationId,tokenId:"CCT",amountRaw:input.amountRaw,recipient:input.recipient,evidenceIds:input.evidence.evidenceIds,metadataUri:input.metadataUri,requiresApproval:true,network:"solana",createdAt:new Date().toISOString()}}
export function cctDeploymentConfig(env:Record<string,string|undefined>){return{mint:env.POWERCHAIN_CCT_MINT?.trim()||null,authority:env.POWERCHAIN_CCT_AUTHORITY?.trim()||null,metadataUri:env.POWERCHAIN_CCT_METADATA_URI?.trim()||null,programs:SOLANA_PROGRAM_IDS,ready:Boolean(env.POWERCHAIN_CCT_MINT?.trim()&&env.POWERCHAIN_CCT_AUTHORITY?.trim())}}
