"use client";
import { useMemo, useState } from "react";
import { ActivityLogIcon, CheckCircledIcon, ClockIcon, LightningBoltIcon, MagnifyingGlassIcon, SewingPinIcon, StarFilledIcon } from "@radix-ui/react-icons";
import { Button } from "@/components/ui/button";
import { demoP2POrders, energyCommunitySummary, localEnergyListings } from "@/data/p2p-energy";
import { calculateTradeTotal, validateP2PQuantity } from "@/lib/p2p";
import type { ListingMode, LocalEnergyListing, P2POrderStatus } from "@/types/p2p";

const modes:{value:ListingMode;label:string}[]=[{value:"sell",label:"Buy energy"},{value:"buy",label:"Sell surplus"},{value:"rent",label:"Rent assets"}];
const money=(value:number,currency="EUR")=>new Intl.NumberFormat("en-FI",{style:"currency",currency,maximumFractionDigits:2}).format(value);

export function P2PMarketplace(){
 const [mode,setMode]=useState<ListingMode>("sell"); const [query,setQuery]=useState(""); const [radius,setRadius]=useState(25); const [selected,setSelected]=useState<LocalEnergyListing|null>(null); const [quantity,setQuantity]=useState(25); const [notice,setNotice]=useState(""); const [tab,setTab]=useState<"market"|"activity">("market");
 const listings=useMemo(()=>localEnergyListings.filter(x=>x.mode===mode&&x.distanceKm<=radius&&(`${x.title} ${x.location} ${x.sellerName}`).toLowerCase().includes(query.toLowerCase())),[mode,query,radius]);
 const totals=selected?calculateTradeTotal(quantity,selected.pricePerKwh):null;
 const quantityError=selected?validateP2PQuantity(quantity,selected.minimumKwh,selected.availableKwh):null;
 async function submit(){if(!selected||quantityError)return; setNotice("Creating metered P2P order…"); const response=await fetch("/api/v1/p2p/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({listingId:selected.id,buyerId:"demo-user",quantityKwh:quantity})}); const body=await response.json(); setNotice(response.ok?`Order ${body.order.id} created. Sign with your Solana wallet to fund escrow.`:body.error??"Unable to create order.");}
 return <div className="space-y-6">
  <section className="overflow-hidden rounded-[28px] border border-emerald-900/10 bg-gradient-to-br from-emerald-950 via-emerald-900 to-emerald-700 p-6 text-white shadow-xl md:p-8"><div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-[.16em]"><LightningBoltIcon/> Local energy community</div><h2 className="mt-5 max-w-2xl text-3xl font-black tracking-tight md:text-5xl">Trade, share, and rent clean energy locally.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-emerald-50/80 md:text-base">Match prosumers and consumers, reserve shared batteries or EV chargers, and settle verified meter delivery through wallet-secured escrow.</p></div><div className="grid grid-cols-2 gap-3 self-end"><Metric label="Community members" value={String(energyCommunitySummary.members)}/><Metric label="Local match rate" value={`${energyCommunitySummary.matchedPercent}%`}/><Metric label="Local supply" value={`${(energyCommunitySummary.localSupplyKwh/1000).toFixed(1)} MWh`}/><Metric label="CO₂ avoided" value={`${(energyCommunitySummary.carbonAvoidedKg/1000).toFixed(1)} t`}/></div></div></section>
  <div className="flex gap-2 border-b border-[var(--border)]"><Tab active={tab==="market"} onClick={()=>setTab("market")}>Marketplace</Tab><Tab active={tab==="activity"} onClick={()=>setTab("activity")}>My energy activity</Tab></div>
  {tab==="activity"?<ActivityPanel/>:<>
  <section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-3 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="flex rounded-xl bg-black/[.04] p-1 dark:bg-white/[.05]">{modes.map(item=><button key={item.value} onClick={()=>{setMode(item.value);setSelected(null)}} className={`rounded-lg px-4 py-2 text-sm font-bold transition ${mode===item.value?"bg-white text-emerald-900 shadow-sm dark:bg-emerald-800 dark:text-white":"muted"}`}>{item.label}</button>)}</div><label className="flex min-w-0 flex-1 items-center gap-2 rounded-xl border border-[var(--border)] px-3"><MagnifyingGlassIcon className="muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search local offers, seller, or city" className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none"/></label><label className="flex items-center gap-3 rounded-xl border border-[var(--border)] px-3 py-2 text-sm"><SewingPinIcon/><span>Within {radius} km</span><input type="range" min="5" max="50" step="5" value={radius} onChange={e=>setRadius(Number(e.target.value))}/></label></div></section>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><section className="grid gap-4 md:grid-cols-2">{listings.map(item=><OfferCard key={item.id} item={item} selected={selected?.id===item.id} onSelect={()=>{setSelected(item);setQuantity(Math.max(item.minimumKwh,Math.min(25,item.availableKwh)));setNotice("")}}/>)}{!listings.length&&<div className="col-span-full rounded-2xl border border-dashed p-10 text-center muted">No local offers match these filters.</div>}</section><aside className="h-fit rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 shadow-sm xl:sticky xl:top-24"><h3 className="text-lg font-extrabold">{mode==="rent"?"Rental reservation":"Metered trade summary"}</h3>{selected?<><p className="mt-1 text-sm muted">{selected.title}</p><div className="mt-3 flex flex-wrap gap-2 text-[11px]"><Pill>{selected.settlementAsset} settlement</Pill><Pill>{selected.meterVerified?"Smart meter verified":"Manual meter"}</Pill></div><label className="mt-5 block text-sm font-bold">{mode==="rent"?"Capacity":"Energy quantity"} (kWh)<input type="number" min={selected.minimumKwh} max={selected.availableKwh} value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="mt-2 h-11 w-full rounded-xl border border-[var(--border)] bg-transparent px-3 outline-none focus:ring-2 focus:ring-emerald-600"/></label>{quantityError&&<p className="mt-2 text-xs text-red-600">{quantityError}</p>}<div className="mt-5 space-y-3 rounded-xl bg-black/[.025] p-4 text-sm dark:bg-white/[.04]"><Row label="Unit price" value={money(selected.pricePerKwh,selected.currency)}/><Row label="Subtotal" value={money(totals?.subtotal??0,selected.currency)}/><Row label="Network fee" value={money(totals?.networkFee??0,selected.currency)}/><Row label="Escrow reserve" value={money(totals?.escrowReserve??0,selected.currency)}/><div className="border-t border-[var(--border)] pt-3"><Row label="Estimated total" value={money(totals?.total??0,selected.currency)} strong/></div></div>{selected.rental&&<p className="mt-3 text-xs muted">Deposit {money(selected.rental.deposit)} · {selected.rental.slotsAvailable} slots · billed per {selected.rental.billingPeriod}</p>}<Button className="mt-5 w-full" size="lg" disabled={Boolean(quantityError)} onClick={submit}>{mode==="rent"?"Reserve and fund escrow":"Continue to wallet signature"}</Button>{notice&&<p className="mt-3 rounded-lg bg-emerald-500/10 p-3 text-xs text-emerald-700 dark:text-emerald-300">{notice}</p>}<p className="mt-3 text-center text-[11px] muted">Escrow releases after smart-meter delivery is verified.</p></>:<div className="mt-8 rounded-xl border border-dashed p-8 text-center text-sm muted">Select a local offer to review pricing, metering, and settlement.</div>}</aside></div></>}
 </div>
}
function ActivityPanel(){return <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex items-center gap-2"><ActivityLogIcon/><h3 className="font-extrabold">Recent local trades</h3></div><div className="mt-4 space-y-3">{demoP2POrders.map(order=><div key={order.id} className="flex flex-col gap-3 rounded-xl border border-[var(--border)] p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-bold">{order.quantityKwh} kWh · {order.settlementAsset}</div><div className="mt-1 text-xs muted">{order.id} · {new Date(order.createdAt).toLocaleString()}</div></div><div className="flex items-center gap-3"><Status status={order.status}/><strong>{money(order.pricing.total,order.currency)}</strong></div></div>)}</div></section><aside className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h3 className="font-extrabold">How settlement works</h3><ol className="mt-4 space-y-4 text-sm"><Step n="1" text="Buyer signs and funds escrow."/><Step n="2" text="Smart meter verifies delivered energy."/><Step n="3" text="Funds release to the producer."/></ol></aside></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.08] p-4 backdrop-blur"><div className="text-xl font-black">{value}</div><div className="mt-1 text-xs text-emerald-50/70">{label}</div></div>}
function OfferCard({item,selected,onSelect}:{item:LocalEnergyListing;selected:boolean;onSelect:()=>void}){return <button onClick={onSelect} className={`rounded-2xl border bg-[var(--surface)] p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${selected?"border-emerald-600 ring-2 ring-emerald-600/15":"border-[var(--border)]"}`}><div className="flex items-start justify-between gap-3"><span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-[11px] font-bold uppercase text-emerald-700 dark:text-emerald-300">{item.source}</span><span className="flex items-center gap-1 text-xs muted"><SewingPinIcon/>{item.distanceKm} km</span></div><h3 className="mt-4 text-lg font-extrabold">{item.title}</h3><p className="mt-1 text-sm muted">{item.sellerName}</p><div className="mt-3 flex flex-wrap items-center gap-3 text-xs"><span className="flex items-center gap-1"><StarFilledIcon className="text-amber-500"/>{item.sellerRating}</span>{item.verified&&<span className="flex items-center gap-1 text-emerald-700"><CheckCircledIcon/>Verified</span>}{item.meterVerified&&<span className="flex items-center gap-1 text-sky-700"><ClockIcon/>Metered</span>}</div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[var(--border)] pt-4"><div><div className="text-xs muted">Available</div><div className="font-extrabold">{item.availableKwh} kWh</div></div><div className="text-right"><div className="text-xs muted">{item.mode==="rent"?"Rental rate":"Energy price"}</div><div className="font-extrabold text-emerald-700">{money(item.pricePerKwh,item.currency)}<span className="text-xs font-medium muted">/{item.mode==="rent"?item.rental?.billingPeriod:"kWh"}</span></div></div></div></button>}
function Row({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={`flex justify-between gap-3 ${strong?"font-extrabold":""}`}><span className="muted">{label}</span><span>{value}</span></div>}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className={`border-b-2 px-3 py-3 text-sm font-bold ${active?"border-emerald-700 text-emerald-800":"border-transparent muted"}`}>{children}</button>}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full bg-black/[.04] px-2 py-1 dark:bg-white/[.06]">{children}</span>}
function Status({status}:{status:P2POrderStatus}){const labels:Record<P2POrderStatus,string>={draft:"Draft",requires_signature:"Signature required",escrowed:"Escrow funded",metering:"Metering",settled:"Settled",cancelled:"Cancelled"};return <span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-bold text-emerald-700">{labels[status]}</span>}
function Step({n,text}:{n:string;text:string}){return <li className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-emerald-700 text-xs font-black text-white">{n}</span><span className="pt-1 muted">{text}</span></li>}
