import { cookies } from "next/headers";
import { getSession } from "@/lib/auth/sessions";
import { SESSION_COOKIE,securityHeaders } from "@/lib/security/security";
export class OperationalApiError extends Error{constructor(readonly code:string,message:string,readonly status=400,readonly details?:unknown){super(message);this.name="OperationalApiError"}}
export async function operationalContext(request:Request){const jar=await cookies();const session=getSession(jar.get(SESSION_COOKIE)?.value);if(!session)throw new OperationalApiError("AUTH_REQUIRED","Authentication is required",401);const requestId=request.headers.get("x-request-id")?.trim()||crypto.randomUUID();const correlationId=request.headers.get("x-correlation-id")?.trim()||requestId;const traceId=request.headers.get("x-trace-id")?.trim()||requestId;return{session,user:session.user,organizationId:session.user.organizationId,requestId,correlationId,traceId,idempotencyKey:request.headers.get("idempotency-key")?.trim()||null}}
export function operationalJson(data:unknown,context:{requestId:string;correlationId:string;traceId:string},init:ResponseInit={}){return Response.json({data,meta:{requestId:context.requestId,correlationId:context.correlationId,traceId:context.traceId}},{...init,headers:{...securityHeaders,"x-request-id":context.requestId,"x-correlation-id":context.correlationId,"x-trace-id":context.traceId,...Object.fromEntries(new Headers(init.headers).entries())}})}
export function operationalError(error:unknown){const known=error instanceof OperationalApiError;const code=known?error.code:error&&typeof error==="object"&&"code" in error?String((error as {code?:unknown}).code):"INTERNAL_ERROR";const status=known?error.status:code.includes("NOT_FOUND")?404:code.includes("CREDITS_INSUFFICIENT")?402:code.includes("CONFLICT")||code.includes("CAS")||code.includes("MISMATCH")?409:code.includes("UNCONFIGURED")||code.includes("_REQUIRED")&&code.startsWith("POWERCHAIN_")?503:code.includes("REQUIRED")||code.includes("INVALID")?422:500;const message=known?error.message:error instanceof Error?error.message:"Unexpected server error";return Response.json({error:{code,message,...(known&&error.details!==undefined?{details:error.details}:{})}},{status,headers:securityHeaders})}
export async function readOperationalJson(request:Request){if(!request.headers.get("content-type")?.includes("application/json"))throw new OperationalApiError("UNSUPPORTED_MEDIA_TYPE","Expected application/json",415);try{return await request.json() as Record<string,unknown>}catch{throw new OperationalApiError("INVALID_JSON","Request body is not valid JSON",400)}}
export function requireIdempotency(context:{idempotencyKey:string|null}){if(!context.idempotencyKey)throw new OperationalApiError("IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key is required for this mutation",400);return context.idempotencyKey}
