import { getSession } from "@/lib/auth/sessions";
import { SESSION_COOKIE,securityHeaders } from "@/lib/security/security";
import type { AuthUser,Session } from "@/types/auth";

export interface ApiContext<T=unknown>{request:Request;requestId:string;traceId:string;correlationId:string;session:Session|null;user:AuthUser|null;organizationId:string|null;body:T;idempotencyKey?:string}
export class ApiError extends Error{constructor(readonly code:string,message:string,readonly status=400,readonly details?:unknown){super(message);this.name="ApiError"}}
function cookie(request:Request,name:string){const raw=request.headers.get("cookie");if(!raw)return null;for(const item of raw.split(";")){const[key,...rest]=item.trim().split("=");if(key===name)return decodeURIComponent(rest.join("="))}return null}
function errorEnvelope(error:unknown){if(error instanceof ApiError)return{code:error.code,message:error.message,status:error.status,details:error.details};const code=error&&typeof error==="object"&&"code" in error?String((error as{code?:unknown}).code):"INTERNAL_ERROR";const message=error instanceof Error?error.message:"Unexpected API error";const status=code.includes("NOT_FOUND")?404:code.includes("UNAUTHORIZED")||code.includes("AUTH_REQUIRED")?401:code.includes("FORBIDDEN")?403:code.includes("CREDITS_INSUFFICIENT")||code.includes("PAYMENT_REQUIRED")?402:code.includes("CONFLICT")||code.includes("REPLAY")||code.includes("DUPLICATE")||code.includes("UNKNOWN")?409:code.includes("UNAVAILABLE")||code.includes("UNCONFIGURED")||code.includes("NOT_READY")?503:code.includes("VALIDATION")||code.includes("REQUIRED")||code.startsWith("ACP-I")?400:500;return{code,message,status}}
export function apiJson(data:unknown,context:Pick<ApiContext,"requestId"|"traceId"|"correlationId"|"organizationId">,init:ResponseInit={}){const headers=new Headers(init.headers);for(const[k,v]of Object.entries(securityHeaders))headers.set(k,v);headers.set("x-request-id",context.requestId);headers.set("x-trace-id",context.traceId);headers.set("x-correlation-id",context.correlationId);return Response.json({data,meta:{apiVersion:"v1",requestId:context.requestId,traceId:context.traceId,correlationId:context.correlationId,organizationId:context.organizationId,observedAt:new Date().toISOString()}},{...init,headers})}
export async function withApi<T=unknown>(request:Request,options:{auth?:"required"|"optional"|"none";json?:boolean;idempotency?:boolean;mutation?:boolean;parse?:(raw:unknown)=>T},handler:(context:ApiContext<T>)=>Promise<Response>|Response){const requestId=request.headers.get("x-request-id")?.trim()||crypto.randomUUID(),traceId=request.headers.get("x-trace-id")?.trim()||requestId,correlationId=request.headers.get("x-correlation-id")?.trim()||requestId;try{const session=options.auth==="none"?null:getSession(cookie(request,SESSION_COOKIE));if((options.auth??"required")==="required"&&!session)throw new ApiError("AUTH_REQUIRED","Authentication is required",401);if(options.mutation&&session){const origin=request.headers.get("origin");if(origin){const requestOrigin=new URL(request.url).origin;const allowed=(process.env.POWERCHAIN_ALLOWED_ORIGINS??requestOrigin).split(",").map(v=>v.trim()).filter(Boolean);if(!allowed.includes(origin))throw new ApiError("ORIGIN_FORBIDDEN","Request origin is not trusted",403)}}let raw:unknown=undefined;if(options.json){const contentType=request.headers.get("content-type")??"";if(!contentType.includes("application/json"))throw new ApiError("UNSUPPORTED_MEDIA_TYPE","Expected application/json",415);try{raw=await request.json()}catch{throw new ApiError("INVALID_JSON","Request body is not valid JSON",400)}}const idempotencyKey=options.idempotency?request.headers.get("idempotency-key")?.trim():undefined;if(options.idempotency&&!idempotencyKey)throw new ApiError("IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key header is required",400);const body=options.parse?options.parse(raw):(raw as T);return await handler({request,requestId,traceId,correlationId,session,user:session?.user??null,organizationId:session?.user.organizationId??null,body,...(idempotencyKey?{idempotencyKey}:{})})}catch(error){const normalized=errorEnvelope(error);const headers=new Headers(securityHeaders);headers.set("x-request-id",requestId);headers.set("x-trace-id",traceId);headers.set("x-correlation-id",correlationId);return Response.json({error:{code:normalized.code,message:normalized.message,...(normalized.details!==undefined?{details:normalized.details}:{})},meta:{apiVersion:"v1",requestId,traceId,correlationId,observedAt:new Date().toISOString()}},{status:normalized.status,headers})}}
