import type { PowerChainChannel } from "../channels/index";
export type RealtimeTransport="websocket"|"sse"|"polling"|"offline";
export interface RealtimeEnvelope<T=unknown>{sequence?:number;organizationId?:string;channel:string;event:string;data:T;sentAt:string;replay?:boolean}
export interface RealtimeClientOptions{baseUrl:string;ticket:()=>Promise<string>;channels:PowerChainChannel[];cursor?:number;pollIntervalMs?:number;onEvent:(event:RealtimeEnvelope)=>void;onTransport?:(transport:RealtimeTransport,detail?:string)=>void;signal?:AbortSignal}
const sleep=(ms:number,signal?:AbortSignal)=>new Promise<void>((resolve,reject)=>{const id=setTimeout(resolve,ms);signal?.addEventListener("abort",()=>{clearTimeout(id);reject(signal.reason)},{once:true})});
export class PowerChainRealtimeClient{
  private stopped=false;private cursor=0;private socket?:WebSocket;private source?:EventSource;
  constructor(private readonly options:RealtimeClientOptions){this.cursor=options.cursor??0}
  async start(){this.stopped=false;let backoff=500;while(!this.stopped&&!this.options.signal?.aborted){try{await this.websocket();backoff=500;continue}catch(error){this.options.onTransport?.("sse",error instanceof Error?error.message:"websocket_unavailable")}try{await this.sse();backoff=500;continue}catch(error){this.options.onTransport?.("polling",error instanceof Error?error.message:"sse_unavailable")}try{await this.polling();backoff=500}catch(error){this.options.onTransport?.("offline",error instanceof Error?error.message:"polling_unavailable");await sleep(backoff,this.options.signal);backoff=Math.min(30_000,Math.round(backoff*1.8))}}}
  stop(){this.stopped=true;this.socket?.close();this.source?.close()}
  private accept(event:RealtimeEnvelope){if(event.sequence&&event.sequence<=this.cursor)return;if(event.sequence)this.cursor=event.sequence;this.options.onEvent(event)}
  private async websocket(){const ticket=await this.options.ticket();const url=new URL(this.options.baseUrl);url.protocol=url.protocol==="https:"?"wss:":"ws:";url.pathname=url.pathname.replace(/\/$/,"")+"/ws";url.searchParams.set("ticket",ticket);url.searchParams.set("cursor",String(this.cursor));return new Promise<void>((resolve,reject)=>{const socket=new WebSocket(url);this.socket=socket;let opened=false;const timeout=setTimeout(()=>{socket.close();reject(new Error("websocket_connect_timeout"))},6000);socket.onopen=()=>{opened=true;clearTimeout(timeout);this.options.onTransport?.("websocket");for(const channel of this.options.channels)socket.send(JSON.stringify({action:"subscribe",channel,after:this.cursor}))};socket.onmessage=event=>{try{const parsed=JSON.parse(String(event.data));if(parsed.channel&&parsed.event&&!['subscribed','connected'].includes(parsed.event))this.accept(parsed)}catch{}};socket.onerror=()=>{if(!opened){clearTimeout(timeout);reject(new Error("websocket_error"))}};socket.onclose=()=>{clearTimeout(timeout);resolve()};this.options.signal?.addEventListener("abort",()=>{socket.close();resolve()},{once:true})})}
  private async sse(){const ticket=await this.options.ticket();const url=new URL(this.options.baseUrl);url.pathname=url.pathname.replace(/\/$/,"")+"/api/v1/realtime/stream";url.searchParams.set("ticket",ticket);url.searchParams.set("channels",this.options.channels.join(","));url.searchParams.set("cursor",String(this.cursor));return new Promise<void>((resolve,reject)=>{const source=new EventSource(url);this.source=source;let opened=false;const timeout=setTimeout(()=>{source.close();reject(new Error("sse_connect_timeout"))},6000);source.onopen=()=>{opened=true;clearTimeout(timeout);this.options.onTransport?.("sse")};source.onmessage=event=>{try{this.accept(JSON.parse(event.data))}catch{}};source.onerror=()=>{clearTimeout(timeout);source.close();opened?resolve():reject(new Error("sse_error"))};this.options.signal?.addEventListener("abort",()=>{source.close();resolve()},{once:true})})}
  private async polling(){this.options.onTransport?.("polling");const ticket=await this.options.ticket();while(!this.stopped&&!this.options.signal?.aborted){const url=new URL(this.options.baseUrl);url.pathname=url.pathname.replace(/\/$/,"")+"/api/v1/realtime/events";url.searchParams.set("ticket",ticket);url.searchParams.set("channels",this.options.channels.join(","));url.searchParams.set("after",String(this.cursor));const response=await fetch(url,{cache:"no-store",signal:AbortSignal.timeout(7000)});if(!response.ok)throw new Error(`polling_http_${response.status}`);const body=await response.json() as{data?:RealtimeEnvelope[]};for(const event of body.data??[])this.accept(event);await sleep(this.options.pollIntervalMs??5000,this.options.signal)}}
}
