import "server-only";
import { getPostgresPool } from "../clients/postgres";
import type { PoolClient } from "pg";
import type { CopilotCreditQuote,CopilotMessagePricingClass } from "@powerchain/credits";

interface AccountRow{id:string;organization_id:string;user_id:string;balance_pwrc_raw:string;reserved_pwrc_raw:string;version:number;created_at:Date;updated_at:Date}
interface ReservationRow{id:string;organization_id:string;account_id:string;request_id:string;quote_id:string;pricing_class:CopilotMessagePricingClass;usd_charge:string;pwrc_usd_price:string;reserved_pwrc_raw:string;settled_pwrc_raw:string;state:"reserved"|"settled"|"released";expires_at:Date;created_at:Date;settled_at:Date|null}
const account=(r:AccountRow)=>({id:r.id,organizationId:r.organization_id,userId:r.user_id,balancePwrcRaw:r.balance_pwrc_raw,reservedPwrcRaw:r.reserved_pwrc_raw,availablePwrcRaw:(BigInt(r.balance_pwrc_raw)-BigInt(r.reserved_pwrc_raw)).toString(),version:r.version,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
const reservation=(r:ReservationRow)=>({id:r.id,organizationId:r.organization_id,accountId:r.account_id,requestId:r.request_id,quoteId:r.quote_id,pricingClass:r.pricing_class,usdCharge:r.usd_charge,pwrcUsdPrice:r.pwrc_usd_price,reservedPwrcRaw:r.reserved_pwrc_raw,settledPwrcRaw:r.settled_pwrc_raw,state:r.state,expiresAt:r.expires_at.toISOString(),createdAt:r.created_at.toISOString(),settledAt:r.settled_at?.toISOString()});

export class CopilotCreditRepository{
 private async transaction<T>(organizationId:string,fn:(client:PoolClient)=>Promise<T>){const client=await getPostgresPool().connect();try{await client.query("begin");await client.query("set transaction isolation level serializable");await client.query("select set_config('app.current_organization_id',$1,true)",[organizationId]);const result=await fn(client);await client.query("commit");return result}catch(error){await client.query("rollback").catch(()=>undefined);throw error}finally{client.release()}}
 async getOrCreateAccount(organizationId:string,userId:string){return this.transaction(organizationId,async client=>{let result=await client.query<AccountRow>(`select * from copilot_credit_accounts where organization_id=$1 and user_id=$2 for update`,[organizationId,userId]);if(!result.rows[0]){result=await client.query<AccountRow>(`insert into copilot_credit_accounts(id,organization_id,user_id) values($1,$2,$3) returning *`,[`cca_${crypto.randomUUID().replaceAll("-","")}`,organizationId,userId])}return account(result.rows[0]!)})}
 async reserve(input:{organizationId:string;userId:string;requestId:string;quote:CopilotCreditQuote}){if(Date.parse(input.quote.expiresAt)<=Date.now())throw Object.assign(new Error("Copilot credit quote expired"),{code:"COPILOT_CREDIT_QUOTE_EXPIRED"});return this.transaction(input.organizationId,async client=>{const existing=await client.query<ReservationRow>(`select * from copilot_credit_reservations where organization_id=$1 and request_id=$2 for update`,[input.organizationId,input.requestId]);if(existing.rows[0])return reservation(existing.rows[0]);let a=await client.query<AccountRow>(`select * from copilot_credit_accounts where organization_id=$1 and user_id=$2 for update`,[input.organizationId,input.userId]);if(!a.rows[0])a=await client.query<AccountRow>(`insert into copilot_credit_accounts(id,organization_id,user_id) values($1,$2,$3) returning *`,[`cca_${crypto.randomUUID().replaceAll("-","")}`,input.organizationId,input.userId]);const row=a.rows[0]!;const required=BigInt(input.quote.pwrcRaw),available=BigInt(row.balance_pwrc_raw)-BigInt(row.reserved_pwrc_raw);if(required>available)throw Object.assign(new Error("Insufficient PWRC Copilot credits"),{code:"COPILOT_CREDITS_INSUFFICIENT",requiredPwrcRaw:required.toString(),availablePwrcRaw:available.toString()});const id=`ccr_${crypto.randomUUID().replaceAll("-","")}`;await client.query(`update copilot_credit_accounts set reserved_pwrc_raw=reserved_pwrc_raw+$1,version=version+1,updated_at=now() where id=$2`,[required.toString(),row.id]);const created=await client.query<ReservationRow>(`insert into copilot_credit_reservations(id,organization_id,account_id,request_id,quote_id,pricing_class,usd_charge,pwrc_usd_price,reserved_pwrc_raw,expires_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *`,[id,input.organizationId,row.id,input.requestId,input.quote.quoteId,input.quote.pricingClass,input.quote.usdCharge,input.quote.pwrcUsdPrice,required.toString(),input.quote.expiresAt]);await client.query(`insert into copilot_credit_ledger_entries(id,organization_id,account_id,entry_type,pwrc_raw,direction,request_id,quote_id,reservation_id,metadata) values($1,$2,$3,'reservation',$4,'hold',$5,$6,$7,$8::jsonb)`,[`ccl_${crypto.randomUUID().replaceAll("-","")}`,input.organizationId,row.id,required.toString(),input.requestId,input.quote.quoteId,id,JSON.stringify({pricingClass:input.quote.pricingClass,usdCharge:input.quote.usdCharge})]);return reservation(created.rows[0]!)})}
 async settle(input:{organizationId:string;reservationId:string;actualPwrcRaw:string;messageId:string;provider?:string;modelId?:string}){return this.transaction(input.organizationId,async client=>{const r=await client.query<ReservationRow>(`select * from copilot_credit_reservations where organization_id=$1 and id=$2 for update`,[input.organizationId,input.reservationId]);const row=r.rows[0];if(!row)throw Object.assign(new Error("Copilot credit reservation not found"),{code:"COPILOT_CREDIT_RESERVATION_NOT_FOUND"});if(row.state==="settled")return reservation(row);if(row.state!=="reserved")throw Object.assign(new Error(`Copilot credit reservation is ${row.state}`),{code:"COPILOT_CREDIT_RESERVATION_INVALID_STATE"});const actual=BigInt(input.actualPwrcRaw),reserved=BigInt(row.reserved_pwrc_raw);if(actual<0n||actual>reserved)throw Object.assign(new Error("Actual Copilot usage exceeds reserved credits"),{code:"COPILOT_CREDIT_SETTLEMENT_EXCEEDS_RESERVATION"});const a=await client.query<AccountRow>(`select * from copilot_credit_accounts where id=$1 and organization_id=$2 for update`,[row.account_id,input.organizationId]);const ar=a.rows[0]!;if(BigInt(ar.balance_pwrc_raw)<actual||BigInt(ar.reserved_pwrc_raw)<reserved)throw Object.assign(new Error("Copilot credit account invariant failed"),{code:"COPILOT_CREDIT_ACCOUNT_INVARIANT"});await client.query(`update copilot_credit_accounts set balance_pwrc_raw=balance_pwrc_raw-$1,reserved_pwrc_raw=reserved_pwrc_raw-$2,version=version+1,updated_at=now() where id=$3`,[actual.toString(),reserved.toString(),row.account_id]);const updated=await client.query<ReservationRow>(`update copilot_credit_reservations set state='settled',settled_pwrc_raw=$3,settled_at=now() where organization_id=$1 and id=$2 returning *`,[input.organizationId,input.reservationId,actual.toString()]);await client.query(`insert into copilot_credit_ledger_entries(id,organization_id,account_id,entry_type,pwrc_raw,direction,request_id,quote_id,reservation_id,metadata) values($1,$2,$3,'settlement',$4,'debit',$5,$6,$7,$8::jsonb)`,[`ccl_${crypto.randomUUID().replaceAll("-","")}`,input.organizationId,row.account_id,actual.toString(),row.request_id,row.quote_id,row.id,JSON.stringify({messageId:input.messageId,provider:input.provider??"",modelId:input.modelId??""})]);const unused=reserved-actual;if(unused>0n)await client.query(`insert into copilot_credit_ledger_entries(id,organization_id,account_id,entry_type,pwrc_raw,direction,request_id,quote_id,reservation_id,metadata) values($1,$2,$3,'release',$4,'release',$5,$6,$7,$8::jsonb)`,[`ccl_${crypto.randomUUID().replaceAll("-","")}`,input.organizationId,row.account_id,unused.toString(),row.request_id,row.quote_id,row.id,JSON.stringify({reason:"unused_reserved_capacity"})]);return reservation(updated.rows[0]!)})}
 async release(input:{organizationId:string;reservationId:string;reason:string}){return this.transaction(input.organizationId,async client=>{const r=await client.query<ReservationRow>(`select * from copilot_credit_reservations where organization_id=$1 and id=$2 for update`,[input.organizationId,input.reservationId]);const row=r.rows[0];if(!row)throw Object.assign(new Error("Copilot credit reservation not found"),{code:"COPILOT_CREDIT_RESERVATION_NOT_FOUND"});if(row.state==="released"||row.state==="settled")return reservation(row);await client.query(`update copilot_credit_accounts set reserved_pwrc_raw=reserved_pwrc_raw-$1,version=version+1,updated_at=now() where id=$2`,[row.reserved_pwrc_raw,row.account_id]);const updated=await client.query<ReservationRow>(`update copilot_credit_reservations set state='released',settled_at=now() where organization_id=$1 and id=$2 returning *`,[input.organizationId,input.reservationId]);await client.query(`insert into copilot_credit_ledger_entries(id,organization_id,account_id,entry_type,pwrc_raw,direction,request_id,quote_id,reservation_id,metadata) values($1,$2,$3,'release',$4,'release',$5,$6,$7,$8::jsonb)`,[`ccl_${crypto.randomUUID().replaceAll("-","")}`,input.organizationId,row.account_id,row.reserved_pwrc_raw,row.request_id,row.quote_id,row.id,JSON.stringify({reason:input.reason})]);return reservation(updated.rows[0]!)})}
 async creditConfirmedDeposit(input:{organizationId:string;userId:string;pwrcRaw:string;externalReference:string;requestId:string}){const amount=BigInt(input.pwrcRaw);if(amount<=0n)throw new Error("Credit deposit must be positive");return this.transaction(input.organizationId,async client=>{const duplicate=await client.query(`select id from copilot_credit_ledger_entries where organization_id=$1 and external_reference=$2`,[input.organizationId,input.externalReference]);if(duplicate.rows[0]){
  const existingAccount=await client.query<AccountRow>(`select * from copilot_credit_accounts where organization_id=$1 and user_id=$2 for update`,[input.organizationId,input.userId]);
  if(existingAccount.rows[0])return account(existingAccount.rows[0]);
}let a=await client.query<AccountRow>(`select * from copilot_credit_accounts where organization_id=$1 and user_id=$2 for update`,[input.organizationId,input.userId]);if(!a.rows[0])a=await client.query<AccountRow>(`insert into copilot_credit_accounts(id,organization_id,user_id) values($1,$2,$3) returning *`,[`cca_${crypto.randomUUID().replaceAll("-","")}`,input.organizationId,input.userId]);await client.query(`update copilot_credit_accounts set balance_pwrc_raw=balance_pwrc_raw+$1,version=version+1,updated_at=now() where id=$2`,[amount.toString(),a.rows[0]!.id]);await client.query(`insert into copilot_credit_ledger_entries(id,organization_id,account_id,entry_type,pwrc_raw,direction,request_id,external_reference,metadata) values($1,$2,$3,'deposit',$4,'credit',$5,$6,'{"source":"confirmed_onchain_or_checkout"}'::jsonb)`,[`ccl_${crypto.randomUUID().replaceAll("-","")}`,input.organizationId,a.rows[0]!.id,amount.toString(),input.requestId,input.externalReference]);const final=await client.query<AccountRow>(`select * from copilot_credit_accounts where id=$1`,[a.rows[0]!.id]);return account(final.rows[0]!)})}
 async ledger(organizationId:string,userId:string,limit=100){const a=await this.getOrCreateAccount(organizationId,userId);const result=await getPostgresPool().query(`select * from copilot_credit_ledger_entries where organization_id=$1 and account_id=$2 order by created_at desc limit $3`,[organizationId,a.id,Math.max(1,Math.min(limit,500))]);return{account:a,entries:result.rows}}
}
