import "server-only";
import { getPostgresPool } from "../clients/postgres";
export type FeedbackValue="helpful"|"unhelpful";
function configured(){return Boolean(process.env.DATABASE_URL?.trim())}
const memorySaved=new Map<string,Set<string>>();const memoryFeedback=new Map<string,{value:FeedbackValue;reason?:string}>();
const memoryChats=new Map<string,{id:string;userId:string;title:string;modelId:string;createdAt:string;updatedAt:string;messages:Array<{id:string;role:"user"|"assistant"|"system";content:string;createdAt:string;metadata:Record<string,unknown>}>}>();
export class CopilotRepository{

async listConversations(userId:string){if(!configured())return[...memoryChats.values()].filter(chat=>chat.userId===userId).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(chat=>({...chat,messageCount:chat.messages.length}));const r=await getPostgresPool().query(`select c.id,c.title,c.model_id,c.created_at,c.updated_at,count(m.id)::int message_count from ai_chats c left join ai_messages m on m.chat_id=c.id where c.user_id=$1 group by c.id order by c.updated_at desc limit 100`,[userId]);return r.rows.map(row=>({id:String(row.id),title:String(row.title),modelId:String(row.model_id),createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString(),messageCount:Number(row.message_count)}))}
async createConversation(userId:string,modelId="powerchain-copilot"){const now=new Date().toISOString();if(!configured()){const chat={id:crypto.randomUUID(),userId,title:"New Copilot conversation",modelId,createdAt:now,updatedAt:now,messages:[]};memoryChats.set(chat.id,chat);return chat}const r=await getPostgresPool().query(`insert into ai_chats(user_id,title,model_id) values($1,'New Copilot conversation',$2) returning id,title,model_id,created_at,updated_at`,[userId,modelId]);const row=r.rows[0];return{id:String(row.id),userId,title:String(row.title),modelId:String(row.model_id),createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString(),messages:[]}}
async conversation(userId:string,conversationId:string){if(!configured()){const chat=memoryChats.get(conversationId);return chat?.userId===userId?chat:null}const c=await getPostgresPool().query(`select id,title,model_id,created_at,updated_at from ai_chats where id=$1 and user_id=$2`,[conversationId,userId]);if(!c.rowCount)return null;const messages=await getPostgresPool().query(`select id,role,content,metadata,created_at from ai_messages where chat_id=$1 and user_id=$2 order by created_at`,[conversationId,userId]);const row=c.rows[0];return{id:String(row.id),userId,title:String(row.title),modelId:String(row.model_id),createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString(),messages:messages.rows.map(message=>({id:String(message.id),role:String(message.role).toLowerCase(),content:String(message.content),createdAt:new Date(message.created_at).toISOString(),metadata:(message.metadata as Record<string,unknown>)??{}}))}}
async addMessage(input:{userId:string;conversationId:string;role:"user"|"assistant"|"system";content:string;metadata?:Record<string,unknown>}){const now=new Date().toISOString();if(!configured()){const chat=memoryChats.get(input.conversationId);if(!chat||chat.userId!==input.userId)throw Object.assign(new Error("Conversation not found"),{code:"COPILOT_CONVERSATION_NOT_FOUND"});const message={id:crypto.randomUUID(),role:input.role,content:input.content,createdAt:now,metadata:input.metadata??{}};chat.messages.push(message);chat.updatedAt=now;if(chat.messages.length===1)chat.title=input.content.slice(0,72)||chat.title;return message}const role=input.role.toUpperCase();const r=await getPostgresPool().query(`insert into ai_messages(chat_id,user_id,role,content,metadata) values($1,$2,$3::"ChatRole",$4,$5::jsonb) returning id,created_at`,[input.conversationId,input.userId,role,input.content,JSON.stringify(input.metadata??{})]);if(!r.rowCount)throw Object.assign(new Error("Conversation not found"),{code:"COPILOT_CONVERSATION_NOT_FOUND"});await getPostgresPool().query(`update ai_chats set updated_at=now(),title=case when (select count(*) from ai_messages where chat_id=$1)=1 then left($3,72) else title end where id=$1 and user_id=$2`,[input.conversationId,input.userId,input.content]);return{id:String(r.rows[0].id),role:input.role,content:input.content,createdAt:new Date(r.rows[0].created_at).toISOString(),metadata:input.metadata??{}}}

 async savedPrompts(userId:string){if(!configured())return[...(memorySaved.get(userId)??new Set())];const r=await getPostgresPool().query(`select prompt_id from copilot_saved_prompts where user_id=$1 order by created_at desc`,[userId]);return r.rows.map(row=>String(row.prompt_id))}
 async savePrompt(userId:string,promptId:string){if(!configured()){const set=memorySaved.get(userId)??new Set<string>();set.add(promptId);memorySaved.set(userId,set);return{promptId}}await getPostgresPool().query(`insert into copilot_saved_prompts(user_id,prompt_id) values($1,$2) on conflict(user_id,prompt_id) do nothing`,[userId,promptId]);return{promptId}}
 async removePrompt(userId:string,promptId:string){if(!configured()){memorySaved.get(userId)?.delete(promptId);return}await getPostgresPool().query(`delete from copilot_saved_prompts where user_id=$1 and prompt_id=$2`,[userId,promptId])}
 async feedback(input:{userId:string;messageId:string;value:FeedbackValue;reason?:string}){if(!configured()){memoryFeedback.set(`${input.userId}:${input.messageId}`,{value:input.value,...(input.reason?{reason:input.reason}:{})});return{messageId:input.messageId,value:input.value}}const owns=await getPostgresPool().query(`select 1 from ai_messages where id=$1 and user_id=$2 and role='ASSISTANT'`,[input.messageId,input.userId]);if(!owns.rowCount)throw Object.assign(new Error("Assistant message not found"),{code:"COPILOT_MESSAGE_NOT_FOUND"});await getPostgresPool().query(`insert into copilot_message_feedback(message_id,user_id,value,reason) values($1,$2,$3,$4) on conflict(message_id,user_id) do update set value=excluded.value,reason=excluded.reason,updated_at=now()`,[input.messageId,input.userId,input.value,input.reason??null]);return{messageId:input.messageId,value:input.value}}
 async deleteConversation(userId:string,conversationId:string){if(!configured()){const chat=memoryChats.get(conversationId);if(chat?.userId!==userId)return false;return memoryChats.delete(conversationId)};const result=await getPostgresPool().query(`delete from ai_chats where id=$1 and user_id=$2`,[conversationId,userId]);return Boolean(result.rowCount)}
}
