import "server-only";
import { getPostgresPool } from "../clients/postgres";
import type { DeviceDigitalTwin, EnergyMonitoringSummary } from "@powerchain/energy-monitoring";

function configured(){return Boolean(process.env.DATABASE_URL?.trim())}
function device(row:Record<string,unknown>):DeviceDigitalTwin{return{
  id:String(row.id),organizationId:String(row.organization_id),...(row.asset_id?{assetId:String(row.asset_id)}:{}),kind:String(row.kind) as DeviceDigitalTwin["kind"],manufacturer:String(row.manufacturer),model:String(row.model),...(row.firmware?{firmware:String(row.firmware)}:{}),...(row.serial_number?{serialNumber:String(row.serial_number)}:{}),status:String(row.status) as DeviceDigitalTwin["status"],network:String(row.network) as DeviceDigitalTwin["network"],...(row.last_seen_at?{lastSeenAt:new Date(String(row.last_seen_at)).toISOString()}:{}),...(row.current_output_w!==null&&row.current_output_w!==undefined?{currentOutputW:BigInt(String(row.current_output_w))}:{}),...(row.cumulative_energy_wh!==null&&row.cumulative_energy_wh!==undefined?{cumulativeEnergyWh:BigInt(String(row.cumulative_energy_wh))}:{}),healthScore:Number(row.health_score??0),metadata:(row.metadata as Record<string,unknown>)??{},
}}
export class EnergyMonitoringRepository{
  readonly mode=configured()?"LIVE":"UNCONFIGURED" as const;
  async listDevices(organizationId:string):Promise<DeviceDigitalTwin[]>{if(!configured())return[];const result=await getPostgresPool().query(`select * from connected_devices where organization_id=$1 order by coalesce(last_seen_at,created_at) desc`,[organizationId]);return result.rows.map(device)}
  async getDevice(organizationId:string,deviceId:string):Promise<(DeviceDigitalTwin&{version:number})|null>{if(!configured())return null;const result=await getPostgresPool().query(`select * from connected_devices where organization_id=$1 and (id::text=$2 or device_id=$2) limit 1`,[organizationId,deviceId]);const row=result.rows[0];return row?{...device(row),version:Number(row.version)}:null}
  async telemetry(organizationId:string,deviceId?:string,limit=200){if(!configured())return[];const result=await getPostgresPool().query(`select dt.id,dt.metric,dt.value::text value,dt.unit,dt.quality,dt.recorded_at,cd.device_id public_device_id,cd.kind from device_telemetry dt join connected_devices cd on cd.id=dt.device_id where cd.organization_id=$1 and ($2::text is null or cd.device_id=$2 or cd.id::text=$2) order by dt.recorded_at desc limit $3`,[organizationId,deviceId??null,Math.max(1,Math.min(limit,1000))]);return result.rows.map(row=>({id:String(row.id),deviceId:String(row.public_device_id),kind:String(row.kind),metric:String(row.metric),value:String(row.value),unit:String(row.unit),quality:String(row.quality),recordedAt:new Date(row.recorded_at).toISOString()}))}
  async summary(organizationId:string):Promise<EnergyMonitoringSummary>{if(!configured())return{verifiedEnergyWh:0n,generationWh:0n,consumptionWh:0n,exportedWh:0n,importedWh:0n,selfConsumptionWh:0n,carbonAvoidedGrams:0n,activeDevices:0,attentionDevices:0,staleDevices:0,observedAt:new Date().toISOString(),sourceMode:"UNCONFIGURED"};const [devices,telemetry]=await Promise.all([getPostgresPool().query(`select count(*) filter(where status='ONLINE') active,count(*) filter(where health_score<80 or status='DEGRADED') attention,count(*) filter(where last_seen_at is null or last_seen_at<now()-interval '15 minutes') stale from connected_devices where organization_id=$1`,[organizationId]),getPostgresPool().query(`select metric,coalesce(sum(value),0)::text total from device_telemetry dt join connected_devices cd on cd.id=dt.device_id where cd.organization_id=$1 and dt.recorded_at>=date_trunc('day',now()) group by metric`,[organizationId])]);const totals=Object.fromEntries(telemetry.rows.map(row=>[String(row.metric),BigInt(String(row.total).split('.')[0]||'0')]));const generationWh=totals.generation_wh??0n,consumptionWh=totals.consumption_wh??0n,exportedWh=totals.exported_wh??0n,importedWh=totals.imported_wh??0n;return{verifiedEnergyWh:totals.verified_energy_wh??generationWh,generationWh,consumptionWh,exportedWh,importedWh,selfConsumptionWh:generationWh>exportedWh?generationWh-exportedWh:0n,carbonAvoidedGrams:totals.carbon_avoided_g??0n,activeDevices:Number(devices.rows[0]?.active??0),attentionDevices:Number(devices.rows[0]?.attention??0),staleDevices:Number(devices.rows[0]?.stale??0),observedAt:new Date().toISOString(),sourceMode:"LIVE"}}
  async createCommand(input:{organizationId:string;deviceId:string;commandType:string;expectedDeviceVersion:number;state:string;reason:string;requestedBy:string;idempotencyKey:string;requestId:string;traceId:string;correlationId:string}){if(!configured())throw Object.assign(new Error("Device command persistence requires DATABASE_URL"),{code:"DEVICE_CONTROL_UNCONFIGURED"});const result=await getPostgresPool().query(`insert into device_commands(organization_id,device_id,command_type,expected_device_version,state,reason,requested_by,idempotency_key,request_id,trace_id,correlation_id) select $1,id,$3,$4,$5,$6,$7,$8,$9,$10,$11 from connected_devices where organization_id=$1 and (id::text=$2 or device_id=$2) returning id,state,created_at`,[input.organizationId,input.deviceId,input.commandType,input.expectedDeviceVersion,input.state,input.reason,input.requestedBy,input.idempotencyKey,input.requestId,input.traceId,input.correlationId]);const row=result.rows[0];if(!row)throw Object.assign(new Error("Connected device not found"),{code:"DEVICE_NOT_FOUND"});return{id:String(row.id),state:String(row.state),createdAt:new Date(row.created_at).toISOString()}}
}
