import "server-only";
import type { PoolClient } from "pg";
import { getPostgresPool } from "../clients/postgres";
import type { LocalEnergyListing,LocalEnergyListingMode,LocalEnergyLifecycle,LocalEnergyReservation } from "@powerchain/local-energy";
function listing(row:any):LocalEnergyListing{return{id:String(row.id),organizationId:String(row.organization_id),participantId:String(row.participant_id),mode:String(row.mode) as LocalEnergyListingMode,source:String(row.source),quantityWh:BigInt(row.quantity_wh),availableWh:BigInt(row.available_wh),priceMinorPerKwh:BigInt(row.price_minor_per_kwh),currency:String(row.currency),deliveryStart:new Date(row.delivery_start).toISOString(),deliveryEnd:new Date(row.delivery_end).toISOString(),version:Number(row.version),state:String(row.state) as LocalEnergyListing["state"]}}
function reservation(row:any):LocalEnergyReservation{return{id:String(row.id),listingId:String(row.listing_id),organizationId:String(row.organization_id),quantityWh:BigInt(row.quantity_wh),listingVersion:Number(row.listing_version),state:String(row.state) as LocalEnergyLifecycle,createdAt:new Date(row.created_at).toISOString()}}
async function tx<T>(organizationId:string,fn:(client:PoolClient)=>Promise<T>){const client=await getPostgresPool().connect();try{await client.query("begin");await client.query("set transaction isolation level serializable");await client.query("select set_config('app.current_organization_id',$1,true)",[organizationId]);const v=await fn(client);await client.query("commit");return v}catch(e){await client.query("rollback").catch(()=>undefined);throw e}finally{client.release()}}
export class LocalEnergyRepository{
 async listReservations(organizationId:string,limit=50){if(!process.env.DATABASE_URL?.trim())return[];const result=await getPostgresPool().query(`select * from local_energy_reservations where organization_id=$1 order by created_at desc limit $2`,[organizationId,Math.max(1,Math.min(limit,200))]);return result.rows.map(reservation)}
 async list(organizationId:string,input:{mode?:LocalEnergyListingMode;source?:string;limit?:number}={}){const result=await getPostgresPool().query(`select * from local_energy_listings where organization_id=$1 and state='ACTIVE' and ($2::text is null or mode=$2) and ($3::text is null or lower(source)=lower($3)) order by delivery_start asc limit $4`,[organizationId,input.mode??null,input.source??null,Math.max(1,Math.min(input.limit??100,200))]);return result.rows.map(listing)}
 async create(input:{organizationId:string;participantId:string;mode:LocalEnergyListingMode;source:string;assetId?:string;quantityWh:bigint;priceMinorPerKwh:bigint;currency:string;deliveryStart:Date;deliveryEnd:Date;metadata?:Record<string,unknown>}){if(input.quantityWh<=0n)throw Object.assign(new Error("Listing quantity must be positive"),{code:"LOCAL_ENERGY_QUANTITY_INVALID"});if(input.deliveryEnd<=input.deliveryStart)throw Object.assign(new Error("Delivery window is invalid"),{code:"LOCAL_ENERGY_WINDOW_INVALID"});const id=`lel_${crypto.randomUUID().replaceAll("-","")}`;const result=await getPostgresPool().query(`insert into local_energy_listings(id,organization_id,participant_id,mode,source,asset_id,quantity_wh,available_wh,price_minor_per_kwh,currency,delivery_start,delivery_end,metadata) values($1,$2,$3,$4,$5,$6,$7,$7,$8,$9,$10,$11,$12::jsonb) returning *`,[id,input.organizationId,input.participantId,input.mode,input.source,input.assetId??null,input.quantityWh.toString(),input.priceMinorPerKwh.toString(),input.currency,input.deliveryStart,input.deliveryEnd,JSON.stringify(input.metadata??{})]);return listing(result.rows[0]!)}
 async reserve(input:{organizationId:string;listingId:string;counterpartyParticipantId:string;quantityWh:bigint;expectedVersion:number;idempotencyKey:string}){return tx(input.organizationId,async client=>{const prior=await client.query(`select * from local_energy_reservations where organization_id=$1 and idempotency_key=$2 for update`,[input.organizationId,input.idempotencyKey]);if(prior.rows[0])return reservation(prior.rows[0]);const locked=await client.query(`select * from local_energy_listings where organization_id=$1 and id=$2 for update`,[input.organizationId,input.listingId]);const current=locked.rows[0];if(!current)throw Object.assign(new Error("Local Energy listing not found"),{code:"LOCAL_ENERGY_LISTING_NOT_FOUND"});if(current.state!=="ACTIVE")throw Object.assign(new Error("Local Energy listing is not active"),{code:"LOCAL_ENERGY_LISTING_NOT_ACTIVE"});if(Number(current.version)!==input.expectedVersion)throw Object.assign(new Error("Local Energy listing version changed"),{code:"LOCAL_ENERGY_VERSION_CONFLICT"});if(input.quantityWh<=0n||input.quantityWh>BigInt(current.available_wh))throw Object.assign(new Error("Requested Wh exceeds available listing quantity"),{code:"LOCAL_ENERGY_INSUFFICIENT_AVAILABLE_WH"});const cas=await client.query(`update local_energy_listings set available_wh=available_wh-$1,version=version+1,updated_at=now() where organization_id=$2 and id=$3 and version=$4 and available_wh >= $1 returning *`,[input.quantityWh.toString(),input.organizationId,input.listingId,input.expectedVersion]);if(!cas.rows[0])throw Object.assign(new Error("Concurrent Local Energy reservation conflict"),{code:"LOCAL_ENERGY_CAS_CONFLICT"});const id=`ler_${crypto.randomUUID().replaceAll("-","")}`;const result=await client.query(`insert into local_energy_reservations(id,organization_id,listing_id,counterparty_participant_id,quantity_wh,listing_version,state,idempotency_key) values($1,$2,$3,$4,$5,$6,'REVIEW_REQUIRED',$7) returning *`,[id,input.organizationId,input.listingId,input.counterpartyParticipantId,input.quantityWh.toString(),input.expectedVersion,input.idempotencyKey]);return reservation(result.rows[0]!)})}
}
