import "server-only";
import { getPostgresPool } from "../clients/postgres";
import type { PoolClient } from "pg";
import type { LocalEnergyListingMode } from "@powerchain/local-energy";

export function databaseConfigured(){return Boolean(process.env.DATABASE_URL?.trim())}
async function transaction<T>(fn:(client:PoolClient)=>Promise<T>){const client=await getPostgresPool().connect();try{await client.query("begin");await client.query("set transaction isolation level serializable");const value=await fn(client);await client.query("commit");return value}catch(error){await client.query("rollback").catch(()=>undefined);throw error}finally{client.release()}}
export function serializeBigints(value:unknown):unknown{if(typeof value==="bigint")return value.toString();if(Array.isArray(value))return value.map(serializeBigints);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[key,serializeBigints(item)]));return value}

export class LocalEnergyRepository{
 async list(organizationId:string,input:{mode?:LocalEnergyListingMode;source?:string;limit?:number}={}){const result=await getPostgresPool().query(`select * from local_energy_listings where organization_id=$1 and state='ACTIVE' and ($2::text is null or mode=$2) and ($3::text is null or lower(source)=lower($3)) order by delivery_start asc limit $4`,[organizationId,input.mode??null,input.source??null,Math.max(1,Math.min(input.limit??100,200))]);return result.rows}
 async create(input:{organizationId:string;participantId:string;mode:LocalEnergyListingMode;source:string;assetId?:string;quantityWh:bigint;priceMinorPerKwh:bigint;currency:string;deliveryStart:Date;deliveryEnd:Date;metadata?:Record<string,unknown>}){if(input.quantityWh<=0n)throw Object.assign(new Error("Listing quantity must be positive"),{code:"LOCAL_ENERGY_QUANTITY_INVALID"});if(input.deliveryEnd<=input.deliveryStart)throw Object.assign(new Error("Delivery window is invalid"),{code:"LOCAL_ENERGY_WINDOW_INVALID"});const id=`lel_${crypto.randomUUID().replaceAll("-","")}`;const result=await getPostgresPool().query(`insert into local_energy_listings(id,organization_id,participant_id,mode,source,asset_id,quantity_wh,available_wh,price_minor_per_kwh,currency,delivery_start,delivery_end,metadata) values($1,$2,$3,$4,$5,$6,$7,$7,$8,$9,$10,$11,$12::jsonb) returning *`,[id,input.organizationId,input.participantId,input.mode,input.source,input.assetId??null,input.quantityWh.toString(),input.priceMinorPerKwh.toString(),input.currency,input.deliveryStart,input.deliveryEnd,JSON.stringify(input.metadata??{})]);return result.rows[0]}
 async reserve(input:{organizationId:string;listingId:string;counterpartyParticipantId:string;quantityWh:bigint;expectedVersion:number;idempotencyKey:string}){return transaction(async client=>{const prior=await client.query(`select * from local_energy_reservations where organization_id=$1 and idempotency_key=$2 for update`,[input.organizationId,input.idempotencyKey]);if(prior.rows[0])return prior.rows[0];const locked=await client.query(`select * from local_energy_listings where organization_id=$1 and id=$2 for update`,[input.organizationId,input.listingId]);const current=locked.rows[0];if(!current)throw Object.assign(new Error("Local Energy listing not found"),{code:"LOCAL_ENERGY_LISTING_NOT_FOUND"});if(current.state!=="ACTIVE")throw Object.assign(new Error("Local Energy listing is not active"),{code:"LOCAL_ENERGY_LISTING_NOT_ACTIVE"});if(Number(current.version)!==input.expectedVersion)throw Object.assign(new Error("Local Energy listing version changed"),{code:"LOCAL_ENERGY_VERSION_CONFLICT"});if(input.quantityWh<=0n||input.quantityWh>BigInt(current.available_wh))throw Object.assign(new Error("Requested Wh exceeds available listing quantity"),{code:"LOCAL_ENERGY_INSUFFICIENT_AVAILABLE_WH"});const updated=await client.query(`update local_energy_listings set available_wh=available_wh-$1,version=version+1,updated_at=now() where organization_id=$2 and id=$3 and version=$4 and available_wh >= $1 returning id`,[input.quantityWh.toString(),input.organizationId,input.listingId,input.expectedVersion]);if(!updated.rows[0])throw Object.assign(new Error("Concurrent Local Energy reservation conflict"),{code:"LOCAL_ENERGY_CAS_CONFLICT"});const id=`ler_${crypto.randomUUID().replaceAll("-","")}`;const result=await client.query(`insert into local_energy_reservations(id,organization_id,listing_id,counterparty_participant_id,quantity_wh,listing_version,state,idempotency_key) values($1,$2,$3,$4,$5,$6,'REVIEW_REQUIRED',$7) returning *`,[id,input.organizationId,input.listingId,input.counterpartyParticipantId,input.quantityWh.toString(),input.expectedVersion,input.idempotencyKey]);return result.rows[0]})}
}

export class OperationsRepository{
 async energyNetwork(organizationId:string,filters:{q?:string;type?:string;limit?:number}={}){const q=filters.q?.trim()||null;const result=await getPostgresPool().query(`select * from energy_network_participants where (public_profile=true or organization_id=$1) and ($2::text is null or name ilike '%'||$2||'%' or participant_type ilike '%'||$2||'%' or array_to_string(capabilities,' ') ilike '%'||$2||'%') and ($3::text is null or participant_type=$3) order by verified desc,name asc limit $4`,[organizationId,q,filters.type??null,Math.max(1,Math.min(filters.limit??50,100))]);return result.rows}
 async emsSummary(organizationId:string){const [assets,meters,devices,alerts,listings,rewards]=await Promise.all([getPostgresPool().query(`select count(*)::int count from energy_assets where organization_id=$1`,[organizationId]),getPostgresPool().query(`select count(*)::int count from smart_meters where organization_id=$1`,[organizationId]).catch(()=>({rows:[{count:0}]} as any)),getPostgresPool().query(`select count(*)::int count from iot_devices where organization_id=$1`,[organizationId]).catch(()=>({rows:[{count:0}]} as any)),getPostgresPool().query(`select count(*)::int count from alerts where organization_id=$1 and status not in ('resolved','closed')`,[organizationId]).catch(()=>({rows:[{count:0}]} as any)),getPostgresPool().query(`select count(*)::int count from local_energy_listings where organization_id=$1 and state='ACTIVE'`,[organizationId]),getPostgresPool().query(`select coalesce(sum(pwrc_raw),0)::text total from reward_allocations where organization_id=$1 and state in ('APPROVED','CLAIMABLE')`,[organizationId])]);return{organizationId,sites:Number(assets.rows[0]?.count??0),meters:Number(meters.rows[0]?.count??0),devices:Number(devices.rows[0]?.count??0),activeAlerts:Number(alerts.rows[0]?.count??0),activeLocalEnergyListings:Number(listings.rows[0]?.count??0),claimablePwrcRaw:String(rewards.rows[0]?.total??"0"),observedAt:new Date().toISOString()}}
 async listTable(table:string,organizationId:string,limit=100){const allowed=new Set(["erp_documents","cmr_relationships","reward_allocations","treasury_accounts","treasury_allocations","vault_records","asset_graph_nodes","asset_graph_relationships","device_command_intents","renewable_revenue_events"]);if(!allowed.has(table))throw new Error("Unsupported operations table");const result=await getPostgresPool().query(`select * from ${table} where organization_id=$1 order by ${table==="treasury_accounts"?"updated_at":"created_at"} desc limit $2`,[organizationId,Math.max(1,Math.min(limit,200))]);return result.rows}
}
