import type { QueryResultRow } from "pg";
import { getPostgresPool } from "../clients/postgres";
import type { RealtimeChannel } from "@powerchain/acp-contracts";

export interface RealtimeEvent<T=unknown>{sequence:number;id:string;organizationId?:string;channel:RealtimeChannel|string;event:string;data:T;requestId?:string;traceId?:string;correlationId?:string;createdAt:string}
export class RealtimeEventRepository{
  async append<T>(input:{organizationId?:string;channel:RealtimeChannel|string;event:string;data:T;requestId?:string;traceId?:string;correlationId?:string;ttlSeconds?:number}){
    const eventId=`rte_${crypto.randomUUID().replaceAll("-","")}`;
    const result=await getPostgresPool().query<{sequence:string;created_at:Date}>(`insert into realtime_events(id,organization_id,channel,event,data,request_id,trace_id,correlation_id,expires_at) values($1,$2,$3,$4,$5::jsonb,$6,$7,$8,now()+($9::text||' seconds')::interval) returning sequence,created_at`,[eventId,input.organizationId??null,input.channel,input.event,JSON.stringify(input.data),input.requestId??null,input.traceId??null,input.correlationId??null,String(input.ttlSeconds??86400)]);
    const sequence=Number(result.rows[0]!.sequence);
    await getPostgresPool().query("select pg_notify('powerchain_realtime',$1)",[JSON.stringify({sequence,organizationId:input.organizationId??null,channel:input.channel})]);
    return{sequence,id:eventId,...input,createdAt:new Date(result.rows[0]!.created_at).toISOString()} satisfies RealtimeEvent<T>;
  }
  async replay(input:{organizationId?:string;channels:string[];after?:number;limit?:number}){
    const limit=Math.max(1,Math.min(input.limit??200,1000));
    const result=await getPostgresPool().query<({sequence:string;id:string;organization_id:string|null;channel:string;event:string;data:unknown;request_id:string|null;trace_id:string|null;correlation_id:string|null;created_at:Date}&QueryResultRow)>(`select sequence,id,organization_id,channel,event,data,request_id,trace_id,correlation_id,created_at from realtime_events where expires_at>now() and sequence>$1 and channel=any($2::text[]) and (organization_id is null or organization_id=$3) order by sequence asc limit $4`,[input.after??0,input.channels,input.organizationId??null,limit]);
    return result.rows.map(row=>({sequence:Number(row.sequence),id:row.id,...(row.organization_id?{organizationId:row.organization_id}:{}),channel:row.channel,event:row.event,data:row.data,...(row.request_id?{requestId:row.request_id}:{}),...(row.trace_id?{traceId:row.trace_id}:{}),...(row.correlation_id?{correlationId:row.correlation_id}:{}),createdAt:new Date(row.created_at).toISOString()}));
  }
  async get(sequence:number){const result=await getPostgresPool().query<({sequence:string;id:string;organization_id:string|null;channel:string;event:string;data:unknown;request_id:string|null;trace_id:string|null;correlation_id:string|null;created_at:Date}&QueryResultRow)>(`select sequence,id,organization_id,channel,event,data,request_id,trace_id,correlation_id,created_at from realtime_events where sequence=$1 and expires_at>now()`,[sequence]);const row=result.rows[0];return row?{sequence:Number(row.sequence),id:row.id,...(row.organization_id?{organizationId:row.organization_id}:{}),channel:row.channel,event:row.event,data:row.data,...(row.request_id?{requestId:row.request_id}:{}),...(row.trace_id?{traceId:row.trace_id}:{}),...(row.correlation_id?{correlationId:row.correlation_id}:{}),createdAt:new Date(row.created_at).toISOString()}:null}
  async replayAll(after:number,limit=500){const result=await getPostgresPool().query<({sequence:string;id:string;organization_id:string|null;channel:string;event:string;data:unknown;request_id:string|null;trace_id:string|null;correlation_id:string|null;created_at:Date}&QueryResultRow)>(`select sequence,id,organization_id,channel,event,data,request_id,trace_id,correlation_id,created_at from realtime_events where expires_at>now() and sequence>$1 order by sequence asc limit $2`,[after,Math.max(1,Math.min(limit,2000))]);return result.rows.map(row=>({sequence:Number(row.sequence),id:row.id,...(row.organization_id?{organizationId:row.organization_id}:{}),channel:row.channel,event:row.event,data:row.data,...(row.request_id?{requestId:row.request_id}:{}),...(row.trace_id?{traceId:row.trace_id}:{}),...(row.correlation_id?{correlationId:row.correlation_id}:{}),createdAt:new Date(row.created_at).toISOString()}))}
  async latestSequence(){const result=await getPostgresPool().query<{sequence:string}>("select coalesce(max(sequence),0)::text sequence from realtime_events");return Number(result.rows[0]?.sequence??0)}
  async prune(){const result=await getPostgresPool().query("delete from realtime_events where expires_at<=now()");return result.rowCount??0}
}
export const realtimeEvents=new RealtimeEventRepository();
