"use client";
import { useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { AlertTriangle,ArrowUpRight,Database,RefreshCw,ShieldCheck } from "lucide-react";
import { Shell } from "@/components/shell";

type Domain="ems"|"erp"|"cmr"|"rewards"|"treasury"|"vault";
type Payload={state:"READY"|"UNCONFIGURED"|"EMPTY";domain:Domain;observedAt:string;metrics:Array<{id:string;label:string;value:string;unit?:string}>;records:Array<Record<string,unknown>>;reason?:string;sourceMode?:string;recentJournals?:Array<Record<string,unknown>>};
const copy:Record<Domain,{eyebrow:string;title:string;description:string;principle:string}>={
 ems:{eyebrow:"ENERGY MANAGEMENT SYSTEM",title:"Operate energy, devices and local markets from one workspace.",description:"Connected energy operations for companies, partnerships, electricity retailers, energy companies, utilities, grid operators and communities.",principle:"Physical meter and device evidence remains authoritative."},
 erp:{eyebrow:"ENERGY ERP",title:"Commercial energy operations and documents.",description:"Invoices, purchase orders, contracts, settlement statements and source-system synchronization remain organization scoped.",principle:"Financial documents never replace settlement or physical-energy evidence."},
 cmr:{eyebrow:"CUSTOMER & MARKET RELATIONSHIPS",title:"Participants, relationships and market interactions.",description:"Manage consumers, prosumers, retailers, utilities, communities, grid operators, partners and service providers.",principle:"Consent and tenant boundaries are evaluated before external activation."},
 rewards:{eyebrow:"POWERCHAIN REWARDS",title:"Evidence-backed PWRC reward allocations.",description:"Track verified-energy, flexibility, DePIN, community and device-reliability rewards without conflating allocation with claim settlement.",principle:"Every reward allocation requires evidence before becoming claimable."},
 treasury:{eyebrow:"TREASURY",title:"Organization-scoped accounting control plane.",description:"Inspect accounts and immutable journal history for suspense, funding, escrow, revenue, reserves and controlled external expenses.",principle:"Posted journals are immutable; corrections use compensating entries."},
 vault:{eyebrow:"POWERCHAIN VAULT",title:"Evidence, policy and audit records.",description:"Durable references for evidence, policy snapshots, documents, audit exports and credential references without storing raw private secrets.",principle:"Private keys, seed phrases and raw credentials are prohibited."},
};
function display(value:unknown){if(value===null||value===undefined)return"—";if(Array.isArray(value))return value.join(", ");if(typeof value==="object")return JSON.stringify(value);return String(value)}
export function DomainOperatorWorkspace({domain}:{domain:Domain}){const[data,setData]=useState<Payload|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);try{const response=await fetch(`/api/v1/operations/${domain}`,{cache:"no-store"});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message??"Workspace unavailable");setData(body.data);setError(null)}catch(cause){setError(cause instanceof Error?cause.message:"Workspace unavailable")}finally{setLoading(false)}},[domain]);useEffect(()=>{void load()},[load]);const meta=copy[domain];return <Shell><main className="pc-page"><div className="pc-container operator-domain-workspace"><header className="operator-domain-header"><div><span className="eyebrow">{meta.eyebrow}</span><h1>{meta.title}</h1><p>{meta.description}</p></div><button type="button" className="pc-button framed" onClick={()=>void load()}><RefreshCw className={loading?"animate-spin":""}/>Refresh</button></header><div className="operator-domain-principle"><ShieldCheck/><span>{meta.principle}</span></div>{error?<section className="operator-domain-state error"><AlertTriangle/><div><strong>Unable to refresh workspace</strong><p>{error}</p><button className="pc-button framed" onClick={()=>void load()}>Retry</button></div></section>:loading&&!data?<section className="operator-domain-skeleton"><i/><i/><i/><i/></section>:data?.state==="UNCONFIGURED"?<section className="operator-domain-state"><Database/><div><strong>Workspace data source is not configured</strong><p>{data.reason??"Configure PostgreSQL and the relevant integration before operational data is displayed."}</p><Link href="/settings/integrations">Configure integrations <ArrowUpRight/></Link></div></section>:<><section className="operator-domain-metrics">{data?.metrics.map(item=><article key={item.id}><span>{item.label}</span><strong>{item.value}</strong>{item.unit&&<small>{item.unit}</small>}</article>)}</section><section className="operator-domain-records"><header><div><span className="eyebrow">CURRENT ORGANIZATION</span><h2>Operational records</h2></div><small>Observed {data?.observedAt?new Date(data.observedAt).toLocaleString():"—"}</small></header>{data?.records?.length?<div className="operator-record-list">{data.records.map((row,index)=><article key={String(row.id??index)}>{Object.entries(row).slice(0,6).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><strong>{display(value)}</strong></div>)}</article>)}</div>:<div className="operator-domain-empty"><strong>No records yet</strong><p>This workspace is connected, but the organization has no records for this module yet.</p></div>}</section></>}</div></main></Shell>}
