"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { AlertTriangle,Database,RefreshCw,Search,ShieldCheck } from "lucide-react";
export function OperatorWorkspace({eyebrow,title,description,endpoint,arrayKeys=[]}:{eyebrow:string;title:string;description:string;endpoint:string;arrayKeys?:string[]}){
 const[data,setData]=useState<Record<string,unknown>|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[q,setQ]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch(endpoint,{cache:"no-store"});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message??body?.error??`Request failed (${response.status})`);setData(body?.data??body);setError("")}catch(cause){setError(cause instanceof Error?cause.message:"Module is unavailable")}finally{setLoading(false)}},[endpoint]);useEffect(()=>{void load()},[load]);
 const state=String(data?.state??(loading?"LOADING":"READY"));const rows=useMemo(()=>{const keys=arrayKeys.length?arrayKeys:Object.keys(data??{});for(const key of keys){const value=data?.[key];if(Array.isArray(value))return value as Record<string,unknown>[]}return[]},[data,arrayKeys]);const filtered=useMemo(()=>{const query=q.trim().toLowerCase();if(!query)return rows;return rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query))},[rows,q]);
 return <div className="space-y-5"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-emerald-700">{eyebrow}</p><h1 className="mt-1 text-3xl font-black tracking-tight">{title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">{description}</p></div><div className="flex items-center gap-2"><Status state={state}/><button type="button" onClick={()=>void load()} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--border)] px-3 text-sm font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button></div></header>
 {loading?<div className="grid gap-3 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-28 animate-pulse rounded-2xl border border-[var(--border)] bg-black/[.025] dark:bg-white/[.03]"/>)}</div>:error?<div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200"><div className="flex items-center gap-2 font-bold"><AlertTriangle className="h-4 w-4"/>Unable to load module</div><p className="mt-2 text-sm">{error}</p></div>:state==="UNCONFIGURED"?<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900/50 dark:bg-amber-950/30"><div className="flex items-center gap-2 font-bold"><Database className="h-4 w-4"/>Workspace unconfigured</div><p className="mt-2 text-sm text-[var(--muted)]">{String(data?.reason??"Connect the canonical PostgreSQL/data source to activate this module. No sample records are synthesized.")}</p></div>:null}
 {data&&state!=="UNCONFIGURED"&&<><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data).filter(([k,v])=>!arrayKeys.includes(k)&&["string","number","boolean"].includes(typeof v)&&k!=="state").slice(0,8).map(([key,value])=><article key={key} className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><p className="text-[11px] font-bold uppercase tracking-wider text-[var(--muted)]">{label(key)}</p><strong className="mt-2 block break-words text-xl font-black tabular-nums">{String(value)}</strong></article>)}</section>{rows.length>0&&<section className="rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><div className="flex flex-col gap-3 border-b border-[var(--border)] p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-extrabold">Records</h2><p className="text-xs text-[var(--muted)]">Tenant-scoped canonical data.</p></div><label className="flex min-h-10 items-center gap-2 rounded-xl border border-[var(--border)] px-3"><Search className="h-4 w-4 text-[var(--muted)]"/><input value={q} onChange={e=>setQ(e.target.value)} className="min-w-0 bg-transparent text-sm outline-none" placeholder="Filter records…"/></label></div><div className="divide-y divide-[var(--border)]">{filtered.slice(0,100).map((row,index)=><RecordRow key={String(row.id??index)} row={row}/>)}</div></section>}{rows.length===0&&state==="EMPTY"&&<div className="rounded-2xl border border-dashed border-[var(--border)] p-10 text-center"><ShieldCheck className="mx-auto h-6 w-6 text-emerald-700"/><h2 className="mt-3 font-bold">No records yet</h2><p className="mt-1 text-sm text-[var(--muted)]">This workspace is connected and currently empty.</p></div>}</>}
 </div>
}
function label(value:string){return value.replace(/([A-Z])/g," $1").replaceAll("_"," ").replace(/^./,m=>m.toUpperCase())}
function Status({state}:{state:string}){const ok=state==="READY"||state==="EMPTY";return <span className={`inline-flex min-h-10 items-center rounded-xl border px-3 text-xs font-extrabold uppercase tracking-wide ${ok?"border-emerald-700/20 bg-emerald-600/10 text-emerald-800":"border-[var(--border)] text-[var(--muted)]"}`}>{state}</span>}
function RecordRow({row}:{row:Record<string,unknown>}){const title=String(row.name??row.label??row.document_type??row.relationship_type??row.account_type??row.reason??row.classification??row.id??"Record");const meta=Object.entries(row).filter(([key,value])=>key!=="id"&&String(value)!==title&&value!==null&&value!==undefined&&typeof value!=="object").slice(0,5);return <article className="min-w-0 p-4"><div className="flex flex-col gap-2 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><strong className="block truncate text-sm">{title}</strong><p className="mt-1 break-all text-xs text-[var(--muted)]">{String(row.id??"")}</p></div><div className="flex flex-wrap gap-2">{meta.map(([key,value])=><span key={key} className="rounded-full border border-[var(--border)] px-2 py-1 text-[10px]"><b>{label(key)}:</b> {String(value)}</span>)}</div></div></article>}
