import type { IntegrationAdapter,IntegrationContext,IntegrationHealth,IntegrationResult } from "../core";

export type HeliusIoTOperation="get_device_asset"|"get_device_assets_by_owner"|"get_program_accounts"|"integration_options";
export interface HeliusIoTRequest{operation:HeliusIoTOperation;payload?:Record<string,unknown>}
export interface HeliusIoTResponse{provider:"helius-iot";operation:HeliusIoTOperation;authority:"ONCHAIN_METADATA_ONLY";payload:unknown;options?:Record<string,unknown>}
function validPubkey(value:string){return /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(value)}
export class HeliusIoTAdapter implements IntegrationAdapter<HeliusIoTRequest,HeliusIoTResponse>{
 readonly provider="helius-iot";
 constructor(private readonly apiKey=process.env.HELIUS_API_KEY?.trim(),private readonly rpcUrl=process.env.HELIUS_RPC_URL?.trim(),private readonly wssUrl=process.env.HELIUS_WSS_URL?.trim()){}
 private endpoint(){if(this.rpcUrl)return this.rpcUrl; if(!this.apiKey)return null;return `https://mainnet.helius-rpc.com/?api-key=${encodeURIComponent(this.apiKey)}`}
 async execute(request:HeliusIoTRequest,context:IntegrationContext):Promise<IntegrationResult<HeliusIoTResponse>>{
  if(request.operation==="integration_options")return{state:"available",source:this.provider,observedAt:new Date().toISOString(),data:{provider:"helius-iot",operation:request.operation,authority:"ONCHAIN_METADATA_ONLY",payload:{},options:{rpc:Boolean(this.endpoint()),websocket:Boolean(this.wssUrl||this.apiKey),das:Boolean(this.endpoint()),webhooks:Boolean(this.apiKey),enhancedTransactions:Boolean(this.apiKey),purpose:["DePIN device identity","Token-2022/SPL asset discovery","program/account observations","on-chain reward/ownership events"],notAuthoritativeFor:["meter readings","physical delivery","device health","energy production"]}}}
  const endpoint=this.endpoint();if(!endpoint)return{state:"misconfigured",source:this.provider,observedAt:new Date().toISOString(),error:{code:"INVALID_CONFIGURATION",message:"HELIUS_API_KEY or HELIUS_RPC_URL is required",retryable:false}};
  const payload=request.payload??{};let method:string;let params:unknown;
  if(request.operation==="get_device_asset"){const id=String(payload.assetId??"");if(!validPubkey(id))return{state:"unavailable",source:this.provider,observedAt:new Date().toISOString(),error:{code:"VALIDATION_FAILED",message:"A valid Solana asset address is required",retryable:false}};method="getAsset";params={id};}
  else if(request.operation==="get_device_assets_by_owner"){const owner=String(payload.ownerAddress??"");if(!validPubkey(owner))return{state:"unavailable",source:this.provider,observedAt:new Date().toISOString(),error:{code:"VALIDATION_FAILED",message:"A valid Solana owner address is required",retryable:false}};method="getAssetsByOwner";params={ownerAddress:owner,page:Number(payload.page??1),limit:Math.min(Number(payload.limit??100),1000)};}
  else if(request.operation==="get_program_accounts"){const programId=String(payload.programId??"");if(!validPubkey(programId))return{state:"unavailable",source:this.provider,observedAt:new Date().toISOString(),error:{code:"VALIDATION_FAILED",message:"A valid Solana program ID is required",retryable:false}};method="getProgramAccounts";params=[programId,{encoding:"base64",commitment:"confirmed"}];}
  else return{state:"unavailable",source:this.provider,observedAt:new Date().toISOString(),error:{code:"VALIDATION_FAILED",message:"Unsupported Helius IoT operation",retryable:false}};
  try{const response=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json","x-request-id":context.requestId},body:JSON.stringify({jsonrpc:"2.0",id:context.requestId,method,params}),signal:context.signal,cache:"no-store"});const body=await response.json().catch(()=>null) as any;if(!response.ok||body?.error)return{state:response.status===429?"degraded":"unavailable",source:this.provider,observedAt:new Date().toISOString(),error:{code:response.status===429?"RATE_LIMITED":"PROVIDER_UNAVAILABLE",message:body?.error?.message??`Helius returned ${response.status}`,retryable:response.status===429||response.status>=500,providerStatus:response.status}};return{state:"available",source:this.provider,observedAt:new Date().toISOString(),data:{provider:"helius-iot",operation:request.operation,authority:"ONCHAIN_METADATA_ONLY",payload:body?.result??body}}}catch(error){return{state:context.signal.aborted?"degraded":"unavailable",source:this.provider,observedAt:new Date().toISOString(),error:{code:context.signal.aborted?"TIMEOUT":"PROVIDER_UNAVAILABLE",message:error instanceof Error?error.message:"Helius IoT request failed",retryable:true}}}
 }
 async health():Promise<IntegrationHealth>{return{provider:this.provider,state:this.endpoint()?"available":"misconfigured",checkedAt:new Date().toISOString()}}
}
