import type { AcpApprovalAction,AcpJob,AcpProposal,ApprovalEnvelope,EffectiveAcpPolicy,Money } from "@powerchain/acp-contracts";
import { assertApprovalUnused } from "@powerchain/acp-domain";
import { acpRepositories,withAcpTransaction,type AcpDatabaseTransaction } from "@powerchain/database/acp";

const id=()=>`apr_${crypto.randomUUID().replaceAll("-","")}`;
export class ApprovalService{
  async requestForJob(input:{organizationId:string;job:AcpJob;action:AcpApprovalAction;proposalHash:string;policy:EffectiveAcpPolicy;amount?:Money;expiresInSeconds?:number;transaction?:AcpDatabaseTransaction}){
    const approval:ApprovalEnvelope={id:id(),organizationId:input.organizationId,resourceType:"job",resourceId:input.job.id,jobId:input.job.id,resourceVersion:input.job.version,proposalHash:input.proposalHash,providerIdentity:input.job.providerIdentityHash,chainId:input.job.chainId,amount:input.amount??{asset:"USDC",rawAmount:"0",decimals:6},asset:"USDC",requirementsHash:input.job.requirementsHash,policySnapshotHash:input.policy.hash,action:input.action,expiresAt:new Date(Date.now()+(input.expiresInSeconds??900)*1000).toISOString(),decision:"pending",createdAt:new Date().toISOString()};
    return acpRepositories.approvals.create({organizationId:input.organizationId,...(input.transaction?{transaction:input.transaction}:{})},approval);
  }
  async requestForProposal(input:{organizationId:string;proposal:AcpProposal;policy:EffectiveAcpPolicy;expiresInSeconds?:number;transaction?:AcpDatabaseTransaction}){
    const approval:ApprovalEnvelope={id:id(),organizationId:input.organizationId,resourceType:"proposal",resourceId:input.proposal.id,resourceVersion:input.proposal.version,proposalHash:input.proposal.requirementsHash,providerIdentity:input.proposal.providerIdentityHash,chainId:input.proposal.chainId,amount:input.proposal.maximumBudget,asset:"USDC",requirementsHash:input.proposal.requirementsHash,policySnapshotHash:input.policy.hash,action:"create_job",expiresAt:new Date(Date.now()+(input.expiresInSeconds??900)*1000).toISOString(),decision:"pending",createdAt:new Date().toISOString()};
    return acpRepositories.approvals.create({organizationId:input.organizationId,...(input.transaction?{transaction:input.transaction}:{})},approval);
  }
  async decide(input:{organizationId:string;approvalId:string;actorId:string;decision:"approved"|"rejected";transaction?:AcpDatabaseTransaction}){return acpRepositories.approvals.decide({organizationId:input.organizationId,...(input.transaction?{transaction:input.transaction}:{})},input.approvalId,input.decision,input.actorId)}
  async consumeJobExact(input:{organizationId:string;approvalId:string;job:AcpJob;policyHash:string;action:AcpApprovalAction;amount?:Money;transaction?:AcpDatabaseTransaction}){
    const work=async(tx:AcpDatabaseTransaction)=>{const context={organizationId:input.organizationId,transaction:tx};const approval=await acpRepositories.approvals.find(context,input.approvalId,true);if(!approval||approval.decision!=="approved")throw Object.assign(new Error("Approved authorization is required"),{code:"ACP_APPROVAL_REQUIRED"});assertApprovalUnused(approval);if(approval.resourceType!=="job"||approval.resourceId!==input.job.id||approval.jobId!==input.job.id||approval.resourceVersion!==input.job.version||approval.providerIdentity!==input.job.providerIdentityHash||approval.chainId!==input.job.chainId||approval.requirementsHash!==input.job.requirementsHash||approval.policySnapshotHash!==input.policyHash||approval.action!==input.action)throw Object.assign(new Error("Approval envelope does not match the exact ACP operation"),{code:"ACP_APPROVAL_BINDING_MISMATCH"});if(input.amount&&approval.amount.rawAmount!==input.amount.rawAmount)throw Object.assign(new Error("Approval amount does not match the exact ACP operation"),{code:"ACP_APPROVAL_AMOUNT_MISMATCH"});return acpRepositories.approvals.consume(context,input.approvalId)};
    return input.transaction?work(input.transaction):withAcpTransaction(input.organizationId,work);
  }
  async consumeProposalExact(input:{organizationId:string;approvalId:string;proposal:AcpProposal;policyHash:string;transaction?:AcpDatabaseTransaction}){
    const work=async(tx:AcpDatabaseTransaction)=>{const context={organizationId:input.organizationId,transaction:tx};const approval=await acpRepositories.approvals.find(context,input.approvalId,true);if(!approval||approval.decision!=="approved")throw Object.assign(new Error("Approved proposal authorization is required"),{code:"ACP_APPROVAL_REQUIRED"});assertApprovalUnused(approval);if(approval.resourceType!=="proposal"||approval.resourceId!==input.proposal.id||approval.resourceVersion!==input.proposal.version||approval.providerIdentity!==input.proposal.providerIdentityHash||approval.chainId!==input.proposal.chainId||approval.requirementsHash!==input.proposal.requirementsHash||approval.policySnapshotHash!==input.policyHash||approval.action!=="create_job")throw Object.assign(new Error("Proposal approval envelope does not match the exact proposal"),{code:"ACP_APPROVAL_BINDING_MISMATCH"});return acpRepositories.approvals.consume(context,input.approvalId)};
    return input.transaction?work(input.transaction):withAcpTransaction(input.organizationId,work);
  }
}
export const approvalService=new ApprovalService();
