import type { SavedPrompt } from "@/types/prompts";
const createdAt="2026-08-25T00:00:00.000Z";
export const COPILOT_PROMPT_LIBRARY:SavedPrompt[]=[
 {id:"ops-health",title:"Operational health",description:"Summarize current operational state and priority exceptions.",prompt:"Summarize operational health. Lead with what requires attention, then explain evidence freshness and the next operator action.",category:"operations",tags:["operations","health","priority"],createdAt,updatedAt:createdAt,system:true},
 {id:"asset-performance",title:"Asset performance",description:"Review selected renewable assets against recent expectations.",prompt:"Analyze my renewable assets. Identify material production variance, health issues, evidence gaps, and recommended follow-up.",category:"assets",tags:["assets","performance","health"],createdAt,updatedAt:createdAt,system:true},
 {id:"energy-balance",title:"Energy balance",description:"Explain generation, consumption, import, export and self-consumption.",prompt:"Review my energy balance for the current period. Separate generation, consumption, import, export, self-consumption, and verified evidence.",category:"energy",tags:["energy","metering","balance"],createdAt,updatedAt:createdAt,system:true},
 {id:"device-triage",title:"Connected device triage",description:"Rank smart meters, inverters and IoT devices needing attention.",prompt:"Review connected-device health and telemetry freshness. Rank devices needing attention and explain why, without issuing device commands.",category:"energy",tags:["devices","iot","smart-meter"],createdAt,updatedAt:createdAt,system:true},
 {id:"treasury-review",title:"Treasury review",description:"Review allocations, suspense and reconciliation state.",prompt:"Review treasury allocation and reconciliation status. Distinguish settlement receipt, suspense, allocation, provider reconciliation, and period-close blockers.",category:"treasury",tags:["treasury","allocation","reconciliation"],createdAt,updatedAt:createdAt,system:true},
 {id:"alerts-priority",title:"Prioritize alerts",description:"Rank current alerts by impact and required action.",prompt:"Prioritize current alerts by severity, impact, evidence confidence, and next action. Do not rely on color alone in the summary.",category:"alerts",tags:["alerts","risk","priority"],createdAt,updatedAt:createdAt,system:true},
 {id:"daily-report",title:"Daily operating report",description:"Prepare a concise auditable daily report.",prompt:"Prepare a daily operating report with energy, devices, assets, alerts, settlement status, evidence freshness, and unresolved actions.",category:"reports",tags:["report","operations","audit"],createdAt,updatedAt:createdAt,system:true},
 {id:"risk-review",title:"Risk review",description:"Evaluate operational and financial control risks.",prompt:"Review current PowerChain risks. Separate physical, operational, financial, blockchain, provider, and AI-control risks and cite the evidence used.",category:"risk",tags:["risk","controls","evidence"],createdAt,updatedAt:createdAt,system:true},
 {id:"token-readiness",title:"Tokenization readiness",description:"Check Energy RWA or carbon-attribute issuance readiness.",prompt:"Review tokenization readiness. Verify physical backing or carbon evidence, reservations, existing representations, compliance controls, and approval requirements.",category:"tokenization",tags:["token-2022","rwa","cct"],createdAt,updatedAt:createdAt,system:true},
 {id:"solar-performance",title:"Solar production review",description:"Analyze solar generation, inverter health and metering.",prompt:"Analyze solar production for connected assets. Compare expected versus observed output and inspect inverter, meter, weather-context, and grid evidence before recommending action.",category:"renewables",tags:["solar","inverter","forecast"],createdAt,updatedAt:createdAt,system:true},
 {id:"grid-flexibility",title:"Grid flexibility",description:"Review dispatchable flexibility and constraints.",prompt:"Review available grid flexibility. Separate physical constraints, storage/DER availability, telemetry freshness, market opportunity, and any action requiring approval.",category:"grid",tags:["grid","flexibility","storage"],createdAt,updatedAt:createdAt,system:true},
 {id:"community-energy",title:"Community energy opportunity",description:"Review local energy and SolarShare opportunities.",prompt:"Review community energy opportunities using verified local generation and consumption. Explain marketplace or peer-to-peer options without creating a trade automatically.",category:"trading",tags:["local-energy","solarshare","p2p"],createdAt,updatedAt:createdAt,system:true},
];
export function findPrompt(id:string){return COPILOT_PROMPT_LIBRARY.find(item=>item.id===id)??null}
