import "server-only";
import { createCipheriv,createDecipheriv,createHmac,randomBytes,timingSafeEqual } from "node:crypto";
import type { AuthUser } from "@/types/auth";
import { runRenewablesAgent } from "@/agents/renewables";
import { TokenizedChatRepository,type EncryptedChatContent,type PersistedChatMessage } from "@powerchain/database/tokenized-chat";
import { CHAT_MESSAGE_REFERENCE_USD,CHAT_MESSAGE_UNIT_BASE_UNITS,CHAT_MESSAGE_UNIT_PWRC,createCanonicalChatQuote,createTokenizedChatProof,hashCanonical,sha256Hex,tokenizedChatProofHash } from "@powerchain/credits";

const repository=new TokenizedChatRepository();
const ENC_KEY_ID="chat-aes256gcm-v1" as const;
const SIGNING_KEY_ID="chat-receipt-hmac-v1" as const;

function requiredKey(name:string){const encoded=process.env[name]?.trim();if(!encoded)throw Object.assign(new Error(`${name} is required for tokenized chat`),{code:`${name}_REQUIRED`});const key=Buffer.from(encoded,"base64");if(key.length!==32)throw Object.assign(new Error(`${name} must decode to exactly 32 bytes`),{code:`${name}_INVALID`});return key}
function encryptionKey(){return requiredKey("POWERCHAIN_CHAT_ENCRYPTION_KEY_B64")}
function signingKey(){return requiredKey("POWERCHAIN_CHAT_RECEIPT_SIGNING_KEY_B64")}
export function encryptChatContent(plaintext:string):EncryptedChatContent{const nonce=randomBytes(12),cipher=createCipheriv("aes-256-gcm",encryptionKey(),nonce);const ciphertext=Buffer.concat([cipher.update(plaintext,"utf8"),cipher.final()]);return{ciphertext:ciphertext.toString("base64"),nonce:nonce.toString("base64"),authTag:cipher.getAuthTag().toString("base64"),contentHash:sha256Hex(plaintext),keyId:ENC_KEY_ID}}
export function decryptChatContent(value:EncryptedChatContent){if(value.keyId!==ENC_KEY_ID)throw Object.assign(new Error("Unsupported chat encryption key ID"),{code:"CHAT_ENCRYPTION_KEY_ID_UNSUPPORTED"});const decipher=createDecipheriv("aes-256-gcm",encryptionKey(),Buffer.from(value.nonce,"base64"));decipher.setAuthTag(Buffer.from(value.authTag,"base64"));const plaintext=Buffer.concat([decipher.update(Buffer.from(value.ciphertext,"base64")),decipher.final()]).toString("utf8");if(sha256Hex(plaintext)!==value.contentHash)throw Object.assign(new Error("Decrypted chat content hash mismatch"),{code:"CHAT_CONTENT_HASH_MISMATCH"});return plaintext}
function signReceiptHash(hash:string){return createHmac("sha256",signingKey()).update(hash).digest("hex")}
function verifyReceiptSignature(hash:string,signature:string){const expected=Buffer.from(signReceiptHash(hash),"hex"),actual=Buffer.from(signature,"hex");return expected.length===actual.length&&timingSafeEqual(expected,actual)}
async function dbUser(user:AuthUser){return repository.resolveUser({email:user.email,displayName:user.name})}
function publicMessage(message:PersistedChatMessage){const content=decryptChatContent(message.encrypted);return{id:message.id,chatId:message.chatId,userId:message.userId,role:message.role.toLowerCase() as "user"|"assistant"|"system",content,createdAt:message.createdAt,status:"complete" as const,...(message.settlementStatus==="SETTLED"&&message.tokenProofHash?{tokenizedProof:{settlementStatus:"SETTLED" as const,messageUnits:1,spentPwrc:CHAT_MESSAGE_UNIT_PWRC,pwrcDebitBaseUnits:CHAT_MESSAGE_UNIT_BASE_UNITS,referenceValueUsd:CHAT_MESSAGE_REFERENCE_USD,receiptId:message.receiptId!,receiptHash:message.receiptHash!,proofHash:message.tokenProofHash,transferable:false,mintedAsset:false,financialInstrument:false}}:{})}}

export class TokenizedChatService{
 async list(user:AuthUser){const userId=await dbUser(user);return repository.listChats(userId)}
 async get(user:AuthUser,conversationId:string){const userId=await dbUser(user),chat=await repository.getChat(userId,conversationId);if(!chat)return null;const messages=await repository.messages(userId,conversationId);return{...chat,messages:messages.map(publicMessage)}}
 async send(input:{user:AuthUser;conversationId?:string;message:string;modelId?:string;requestId:string;signal?:AbortSignal}){
  const userId=await dbUser(input.user);let chat=input.conversationId?await repository.getChat(userId,input.conversationId):null;if(input.conversationId&&!chat)throw Object.assign(new Error("Conversation not found"),{code:"CHAT_NOT_FOUND"});if(!chat)chat=await repository.createChat(userId,input.modelId??"powerchain-copilot",input.message.slice(0,72)||"PowerChain conversation");
  const createdAt=new Date().toISOString(),expiresAt=new Date(Date.now()+2*60_000).toISOString();const quotePayload=createCanonicalChatQuote({conversationId:chat.id,userId,requestId:input.requestId,createdAt,expiresAt}),quoteHash=hashCanonical(quotePayload);const quote=await repository.persistQuote({userId,chatId:chat.id,requestId:input.requestId,quoteHash,canonicalPayload:quotePayload,expiresAt});const persistedQuoteHash=quote.quoteHash;const reservation=await repository.reserve({userId,chatId:chat.id,quoteId:quote.id,quoteHash:persistedQuoteHash,requestId:input.requestId,expiresAt:quote.expiresAt});
  if(reservation.state==="SETTLED"){const messages=await repository.messages(userId,chat.id);const settled=messages.find(item=>item.role==="ASSISTANT"&&item.reservationId===reservation.id);return{chatId:chat.id,userId,messages:messages.map(publicMessage),settlement:settled?{messageId:settled.id,quoteHash:settled.quoteHash!,reservationId:reservation.id,receiptId:settled.receiptId!,receiptHash:settled.receiptHash!,proofHash:settled.tokenProofHash!,pwrcDebitBaseUnits:CHAT_MESSAGE_UNIT_BASE_UNITS,spentPwrc:CHAT_MESSAGE_UNIT_PWRC,messageUnits:1,referenceValueUsd:CHAT_MESSAGE_REFERENCE_USD}:{state:"SETTLED"}}}
  if(reservation.state==="RELEASED")throw Object.assign(new Error("This idempotency key belongs to a released chat reservation"),{code:"CHAT_IDEMPOTENCY_REPLAY_RELEASED"});
  await repository.addEncryptedMessage({userId,chatId:chat.id,role:"USER",encrypted:encryptChatContent(input.message),quoteHash:persistedQuoteHash,reservationId:reservation.id,metadata:{requestId:input.requestId,tokenizedBilling:true}});
  try{
   if(input.signal?.aborted)throw Object.assign(new Error("Generation cancelled"),{code:"CHAT_GENERATION_CANCELLED"});
   const result=await runRenewablesAgent({prompt:input.message});if(input.signal?.aborted)throw Object.assign(new Error("Generation cancelled"),{code:"CHAT_GENERATION_CANCELLED"});const response=`${result.summary}\n\n${result.recommendations.map((item,index)=>`${index+1}. ${item}`).join("\n")}`;const responseHash=sha256Hex(response),messageId=crypto.randomUUID(),messageUnitId=`unit_${crypto.randomUUID().replaceAll("-","")}`,receiptId=`rcpt_${crypto.randomUUID().replaceAll("-","")}`,issuedAt=new Date().toISOString();const receiptBody={version:"1.0.0",kind:"POWERCHAIN_COPILOT_SETTLEMENT_RECEIPT",conversationId:chat.id,messageId,quoteHash:persistedQuoteHash,reservationId:reservation.id,responseHash,messageUnitId,messageUnits:1,pwrcDebitBaseUnits:CHAT_MESSAGE_UNIT_BASE_UNITS,spentPwrc:CHAT_MESSAGE_UNIT_PWRC,referenceValueUsd:CHAT_MESSAGE_REFERENCE_USD,settlementStatus:"SETTLED",transferable:false,mintedAsset:false,financialInstrument:false,issuedAt};const receiptHash=hashCanonical(receiptBody),signature=signReceiptHash(receiptHash);const proof=createTokenizedChatProof({conversationId:chat.id,messageId,quoteHash:persistedQuoteHash,reservationId:reservation.id,responseId:messageId,responseHash,receiptId,receiptHash,messageUnitId}),proofHash=tokenizedChatProofHash(proof);const settled=await repository.settleAssistant({messageId,userId,chatId:chat.id,reservationId:reservation.id,quoteHash:persistedQuoteHash,encrypted:encryptChatContent(response),responseHash,receipt:{id:receiptId,hash:receiptHash,signature,signingKeyId:SIGNING_KEY_ID,issuedAt},proof:{id:`proof_${crypto.randomUUID().replaceAll("-","")}`,value:proof,hash:proofHash},metadata:{requestId:input.requestId,confidence:result.confidence,assetIds:result.assetIds,receiptSemantics:{transferable:false,mintedAsset:false,financialInstrument:false}}});const messages=await repository.messages(userId,chat.id);return{chatId:chat.id,userId,messages:messages.map(publicMessage),settlement:{messageId:settled.id,quoteHash:persistedQuoteHash,reservationId:reservation.id,receiptId,receiptHash,proofHash,pwrcDebitBaseUnits:CHAT_MESSAGE_UNIT_BASE_UNITS,spentPwrc:CHAT_MESSAGE_UNIT_PWRC,messageUnits:1,referenceValueUsd:CHAT_MESSAGE_REFERENCE_USD}};
  }catch(error){await repository.releaseReservation({userId,reservationId:reservation.id,reason:error&&typeof error==="object"&&"code" in error?String((error as{code?:unknown}).code):"generation_failed"}).catch(()=>undefined);throw error}
 }
 async credits(user:AuthUser,conversationId:string){const userId=await dbUser(user);return repository.conversationCredits(userId,conversationId)}
 async account(user:AuthUser){const userId=await dbUser(user);return repository.creditAccount(userId)}
 async proof(user:AuthUser,conversationId:string,messageId:string){const userId=await dbUser(user);const record=await repository.proof(userId,conversationId,messageId);if(!record)return null;const recomputedProofHash=tokenizedChatProofHash(record.proof);const receiptBody={version:"1.0.0",kind:"POWERCHAIN_COPILOT_SETTLEMENT_RECEIPT",conversationId,messageId,quoteHash:record.proof.quoteHash,reservationId:record.proof.reservationId,responseHash:record.proof.responseHash,messageUnitId:record.proof.messageUnitId,messageUnits:1,pwrcDebitBaseUnits:CHAT_MESSAGE_UNIT_BASE_UNITS,spentPwrc:CHAT_MESSAGE_UNIT_PWRC,referenceValueUsd:CHAT_MESSAGE_REFERENCE_USD,settlementStatus:"SETTLED",transferable:false,mintedAsset:false,financialInstrument:false,issuedAt:record.issuedAt};const recomputedReceiptHash=hashCanonical(receiptBody);return{...record,verification:{proofHashValid:recomputedProofHash===record.proofHash,receiptHashValid:recomputedReceiptHash===record.proof.receiptHash,receiptSignatureValid:verifyReceiptSignature(record.proof.receiptHash,record.signature),semanticsValid:record.proof.settlementStatus==="SETTLED"&&!record.proof.transferable&&!record.proof.mintedAsset&&!record.proof.financialInstrument},receiptSemantics:{settlementStatus:"SETTLED",transferable:false,mintedAsset:false,financialInstrument:false,description:"Non-transferable cryptographic receipt reference. It is not a minted asset, NFT, security, or other financial instrument."}}}
}
export const tokenizedChatService=new TokenizedChatService();
